//
//  Headers.h
//  MW_SDK
//
//  Created by Gan Yuanrong on 2022/10/22.
//  Copyright © 2022 Gama. All rights reserved.
//

#ifndef Headers_h
#define Headers_h

#define wwwww_tag_wwwww_serverTimestamp        @"serverTimestamp"  //@"serverTimestamp"
#define wwwww_tag_wwwww_install        @"install"  //@"install"
#define wwwww_tag_wwwww_userId        @"userId"  //@"userId"
#define wwwww_tag_wwwww_time        @"time"  //@"time"
#define wwwww_tag_wwwww_role_name        @"role_name"  //@"role_name"
#define wwwww_tag_wwwww_role_id        @"role_id"  //@"role_id"
#define wwwww_tag_wwwww_idfa        @"idfa"  //@"idfa"
#define wwwww_tag_wwwww_uniqueId        @"uniqueId"  //@"uniqueId"
#define wwwww_tag_wwwww_platform        @"platform"  //@"platform"
#define wwwww_tag_wwwww_ios        @"ios"  //@"ios"
#define wwwww_tag_wwwww_USD        @"USD"  //@"USD"
#define wwwww_tag_wwwww_SDK_LOGIN_SUCCUESS        @"SDK_LOGIN_SUCCUESS"  //@"SDK_LOGIN_SUCCUESS"
#define wwwww_tag_wwwww_GAMAPHCHASESUCCESSFUL        @"GAMAPHCHASESUCCESSFUL"  //@"GAMAPHCHASESUCCESSFUL"
#define wwwww_tag_wwwww_GAMAPHCHASEFAIL        @"GAMAPHCHASEFAIL"  //@"GAMAPHCHASEFAIL"
#define wwwww_tag_wwwww_GAMAPHCHASING        @"GAMAPHCHASING"  //@"GAMAPHCHASING"
#define wwwww_tag_wwwww_CONST_GAMA_SHARE_RESULT        @"CONST_GAMA_SHARE_RESULT"  //@"CONST_GAMA_SHARE_RESULT"
#define wwwww_tag_wwwww_GAMA_NOTICE_CLOSE        @"GAMA_NOTICE_CLOSE"  //@"GAMA_NOTICE_CLOSE"
#define wwwww_tag_wwwww_neg_pretiproof        @"请在主线程调用该接口"  //@"请在主线程调用该接口"
#define wwwww_tag_wwwww_gloriistic_diamisslike        @"正在充值中..."  //@"正在充值中..."
#define wwwww_tag_wwwww_meraceous_nugaciular        @"当前版本不支持该功能"  //@"当前版本不支持该功能"
#define wwwww_tag_wwwww_text_area_code_not_empty        @"text_area_code_not_empty"  //@"text_area_code_not_empty"
#define wwwww_tag_wwwww_text_phone_not_empty        @"text_phone_not_empty"  //@"text_phone_not_empty"
#define wwwww_tag_wwwww_text_phone_not_match        @"text_phone_not_match"  //@"text_phone_not_match"
#define wwwww_tag_wwwww_text_vfcode_has_send        @"text_vfcode_has_send"  //@"text_vfcode_has_send"
#define wwwww_tag_wwwww_py_msg_vfcode_hint        @"py_msg_vfcode_hint"  //@"py_msg_vfcode_hint"
#define wwwww_tag_wwwww_text_phone_bind_success        @"text_phone_bind_success"  //@"text_phone_bind_success"
#define wwwww_tag_wwwww_text_select_account        @"text_select_account"  //@"text_select_account"
#define wwwww_tag_wwwww_text_account_bind_success2        @"text_account_bind_success2"  //@"text_account_bind_success2"
#define wwwww_tag_wwwww_openCs__        @"openCs.."  //@"openCs.."
#define wwwww_tag_wwwww_addLocalNotificationWithTitle        @"addLocalNotificationWithTitle"  //@"addLocalNotificationWithTitle"
#define wwwww_tag_wwwww_Alert_ActivityGoalAttained_Salient_Haptic_caf        @"Alert_ActivityGoalAttained_Salient_Haptic.caf"  //@"Alert_ActivityGoalAttained_Salient_Haptic.caf"
#define wwwww_tag_wwwww_octogesimserveation_cause        @"你已经10秒没出现了"  //@"你已经10秒没出现了"
#define wwwww_tag_wwwww_noticeId        @"noticeId"  //@"noticeId"
#define wwwww_tag_wwwww_00001        @"00001"  //@"00001"
#define wwwww_tag_wwwww_APP_OPEN        @"APP_OPEN"  //@"APP_OPEN"
#define wwwww_tag_wwwww_LOGIN_SUCCESS        @"LOGIN_SUCCESS"  //@"LOGIN_SUCCESS"
#define wwwww_tag_wwwww_REGISTER_SUCCESS        @"REGISTER_SUCCESS"  //@"REGISTER_SUCCESS"
#define wwwww_tag_wwwww_OPEN_LOGIN_SCREEN        @"OPEN_LOGIN_SCREEN"  //@"OPEN_LOGIN_SCREEN"
#define wwwww_tag_wwwww_FIRST_PURCHASE        @"FIRST_PURCHASE"  //@"FIRST_PURCHASE"
#define wwwww_tag_wwwww_COMPLETE_REGISTRATION_IOS        @"COMPLETE_REGISTRATION_IOS"  //@"COMPLETE_REGISTRATION_IOS"
#define wwwww_tag_wwwww_CHECK_PERMISSIONS        @"CHECK_PERMISSIONS"  //@"CHECK_PERMISSIONS"
#define wwwww_tag_wwwww_CHECK_UPDATE        @"CHECK_UPDATE"  //@"CHECK_UPDATE"
#define wwwww_tag_wwwww_CHECK_RESOURCES        @"CHECK_RESOURCES"  //@"CHECK_RESOURCES"
#define wwwww_tag_wwwww_SELECT_SERVER        @"SELECT_SERVER"  //@"SELECT_SERVER"
#define wwwww_tag_wwwww_CREATE_ROLE        @"CREATE_ROLE"  //@"CREATE_ROLE"
#define wwwww_tag_wwwww_START_GUIDE        @"START_GUIDE"  //@"START_GUIDE"
#define wwwww_tag_wwwww_COMPLETE_GUIDE        @"COMPLETE_GUIDE"  //@"COMPLETE_GUIDE"
#define wwwww_tag_wwwww_didFinishLaunchingWithOptions        @"didFinishLaunchingWithOptions"  //@"didFinishLaunchingWithOptions"
#define wwwww_tag_wwwww_token        @"token"  //@"token"
#define wwwww_tag_wwwww_FCMToken        @"FCMToken"  //@"FCMToken"
#define wwwww_tag_wwwww_didReceiveNotificationResponse        @"didReceiveNotificationResponse"  //@"didReceiveNotificationResponse"
#define wwwww_tag_wwwww_gcm_message_id        @"gcm.message_id"  //@"gcm.message_id"
#define wwwww_tag_wwwww_AppsFlyerTracker        @"AppsFlyerTracker"  //@"AppsFlyerTracker"
#define wwwww_tag_wwwww_sharedTracker        @"sharedTracker"  //@"sharedTracker"
#define wwwww_tag_wwwww_FIRMessaging        @"FIRMessaging"  //@"FIRMessaging"
#define wwwww_tag_wwwww_messaging        @"messaging"  //@"messaging"
#define wwwww_tag_wwwww_public_profile        @"public_profile"  //@"public_profile"
#define wwwww_tag_wwwww_loadCurrentProfileWithCompletion        @"loadCurrentProfileWithCompletion"  //@"loadCurrentProfileWithCompletion"
#define wwwww_tag_wwwww_error        @"error"  //@"error"
#define wwwww_tag_wwwww_sharerDidCancel        @"sharerDidCancel"  //@"sharerDidCancel"
#define wwwww_tag_wwwww_cancel        @"cancel"  //@"cancel"
#define wwwww_tag_wwwww_profile        @"profile"  //@"profile"
#define wwwww_tag_wwwww_allVersion        @"allVersion"  //@"allVersion"
#define wwwww_tag_wwwww_subVersion        @"subVersion"  //@"subVersion"
#define wwwww_tag_wwwww_url        @"url"  //@"url"
#define wwwww_tag_wwwww_eventName        @"eventName"  //@"eventName"
#define wwwww_tag_wwwww_appTime        @"appTime"  //@"appTime"
#define wwwww_tag_wwwww_gameCode        @"gameCode"  //@"gameCode"
#define wwwww_tag_wwwww_signature        @"signature"  //@"signature"
#define wwwww_tag_wwwww_timestamp        @"timestamp"  //@"timestamp"
#define wwwww_tag_wwwww_registPlatform        @"registPlatform"  //@"registPlatform"
#define wwwww_tag_wwwww_loginMode        @"loginMode"  //@"loginMode"
#define wwwww_tag_wwwww_thirdPlatId        @"thirdPlatId"  //@"thirdPlatId"
#define wwwww_tag_wwwww_thirdLoginId        @"thirdLoginId"  //@"thirdLoginId"
#define wwwww_tag_wwwww_loginId        @"loginId"  //@"loginId"
#define wwwww_tag_wwwww_password        @"password"  //@"password"
#define wwwww_tag_wwwww_phone        @"phone"  //@"phone"
#define wwwww_tag_wwwww_phoneAreaCode        @"phoneAreaCode"  //@"phoneAreaCode"
#define wwwww_tag_wwwww_email        @"email"  //@"email"
#define wwwww_tag_wwwww_interfaces        @"interfaces"  //@"interfaces"
#define wwwww_tag_wwwww_telephone        @"telephone"  //@"telephone"
#define wwwww_tag_wwwww_areaCode        @"areaCode"  //@"areaCode"
#define wwwww_tag_wwwww_vCode        @"vCode"  //@"vCode"
#define wwwww_tag_wwwww_packageName        @"packageName"  //@"packageName"
#define wwwww_tag_wwwww_adId        @"adId"  //@"adId"
#define wwwww_tag_wwwww_uuid        @"uuid"  //@"uuid"
#define wwwww_tag_wwwww_versionName        @"versionName"  //@"versionName"
#define wwwww_tag_wwwww_versionCode        @"versionCode"  //@"versionCode"
#define wwwww_tag_wwwww_systemVersion        @"systemVersion"  //@"systemVersion"
#define wwwww_tag_wwwww_osVersion        @"osVersion"  //@"osVersion"
#define wwwww_tag_wwwww_deviceType        @"deviceType"  //@"deviceType"
#define wwwww_tag_wwwww_os        @"os"  //@"os"
#define wwwww_tag_wwwww_gameLanguage        @"gameLanguage"  //@"gameLanguage"
#define wwwww_tag_wwwww_osLanguage        @"osLanguage"  //@"osLanguage"
#define wwwww_tag_wwwww_loginTimestamp        @"loginTimestamp"  //@"loginTimestamp"
#define wwwww_tag_wwwww_accessToken        @"accessToken"  //@"accessToken"
#define wwwww_tag_wwwww_appsflyerId        @"appsflyerId"  //@"appsflyerId"
#define wwwww_tag_wwwww_loginAccessToken        @"loginAccessToken"  //@"loginAccessToken"
#define wwwww_tag_wwwww_serverCode        @"serverCode"  //@"serverCode"
#define wwwww_tag_wwwww_serverName        @"serverName"  //@"serverName"
#define wwwww_tag_wwwww_roleId        @"roleId"  //@"roleId"
#define wwwww_tag_wwwww_roleName        @"roleName"  //@"roleName"
#define wwwww_tag_wwwww_roleLevel        @"roleLevel"  //@"roleLevel"
#define wwwww_tag_wwwww_roleVipLevel        @"roleVipLevel"  //@"roleVipLevel"
#define wwwww_tag_wwwww_vfCode        @"vfCode"  //@"vfCode"
#define wwwww_tag_wwwww_name        @"name"  //@"name"
#define wwwww_tag_wwwww_oldPwd        @"oldPwd"  //@"oldPwd"
#define wwwww_tag_wwwww_newPwd        @"newPwd"  //@"newPwd"
#define wwwww_tag_wwwww_verifyCode        @"verifyCode"  //@"verifyCode"
#define wwwww_tag_wwwww_2        @"2"  //@"2"
#define wwwww_tag_wwwww_payType        @"payType"  //@"payType"
#define wwwww_tag_wwwww_apple        @"apple"  //@"apple"
#define wwwww_tag_wwwww_mode        @"mode"  //@"mode"
#define wwwww_tag_wwwww_productId        @"productId"  //@"productId"
#define wwwww_tag_wwwww_extra        @"extra"  //@"extra"
#define wwwww_tag_wwwww_cpOrderId        @"cpOrderId"  //@"cpOrderId"
#define wwwww_tag_wwwww_orderId        @"orderId"  //@"orderId"
#define wwwww_tag_wwwww_transactionId        @"transactionId"  //@"transactionId"
#define wwwww_tag_wwwww_receiptData        @"receiptData"  //@"receiptData"
#define wwwww_tag_wwwww_reissue        @"reissue"  //@"reissue"
#define wwwww_tag_wwwww_89bc52ca5b        @"89bc52ca5b"  //@"89bc52ca5b"
#define wwwww_tag_wwwww_1        @"1"  //@"1"
#define wwwww_tag_wwwww_data        @"data"  //@"data"
#define wwwww_tag_wwwww_py_error_occur        @"py_error_occur"  //@"py_error_occur"
#define wwwww_tag_wwwww_status        @"status"  //@"status"
#define wwwww_tag_wwwww_ok        @"ok"  //@"ok"
#define wwwww_tag_wwwww_accountName        @"accountName"  //@"accountName"
#define wwwww_tag_wwwww_accountPwd        @"accountPwd"  //@"accountPwd"
#define wwwww_tag_wwwww_lastLoginTimemobile        @"lastLoginTimemobile"  //@"lastLoginTimemobile"
#define wwwww_tag_wwwww_thirdId        @"thirdId"  //@"thirdId"
#define wwwww_tag_wwwww_thirdAccount        @"thirdAccount"  //@"thirdAccount"
#define wwwww_tag_wwwww_accountIsBind        @"accountIsBind"  //@"accountIsBind"
#define wwwww_tag_wwwww_loginType        @"loginType"  //@"loginType"
#define wwwww_tag_wwwww_sign        @"sign"  //@"sign"
#define wwwww_tag_wwwww_isBindPhone        @"isBindPhone"  //@"isBindPhone"
#define wwwww_tag_wwwww_GAMA_LAST_GUEST_LOGIN_USER_INFO_KEY        @"GAMA_LAST_GUEST_LOGIN_USER_INFO_KEY"  //@"GAMA_LAST_GUEST_LOGIN_USER_INFO_KEY"
#define wwwww_tag_wwwww_GAMA_NOTE_SAVE_PHOTO        @"GAMA_NOTE_SAVE_PHOTO"  //@"GAMA_NOTE_SAVE_PHOTO"
#define wwwww_tag_wwwww_GAMAENKEY        @"GAMAENKEY"  //@"GAMAENKEY"
#define wwwww_tag_wwwww_GAMAENIV        @"GAMAENIV"  //@"GAMAENIV"
#define wwwww_tag_wwwww_Helvetica        @"Helvetica"  //@"Helvetica"
#define wwwww_tag_wwwww_SDK_PHONE_AREA_CODE        @"SDK_PHONE_AREA_CODE"  //@"SDK_PHONE_AREA_CODE"
#define wwwww_tag_wwwww_py_account_empty        @"py_account_empty"  //@"py_account_empty"
#define wwwww_tag_wwwww_text_account_format        @"text_account_format"  //@"text_account_format"
#define wwwww_tag_wwwww_py_password_empty        @"py_password_empty"  //@"py_password_empty"
#define wwwww_tag_wwwww_text_pwd_format        @"text_pwd_format"  //@"text_pwd_format"
#define wwwww_tag_wwwww__CC_000000        @"#000000"  //@"#000000"
#define wwwww_tag_wwwww_auct_conditionit        @"保存guest账号密码截图到相册"  //@"保存guest账号密码截图到相册"
#define wwwww_tag_wwwww_TXT_GUEST_SAVE_IMAGE_OR_NOT        @"TXT_GUEST_SAVE_IMAGE_OR_NOT"  //@"TXT_GUEST_SAVE_IMAGE_OR_NOT"
#define wwwww_tag_wwwww_BTN_TITLE_TXT_CANCEL        @"BTN_TITLE_TXT_CANCEL"  //@"BTN_TITLE_TXT_CANCEL"
#define wwwww_tag_wwwww_BTN_TITLE_TXT_COMFIRM        @"BTN_TITLE_TXT_COMFIRM"  //@"BTN_TITLE_TXT_COMFIRM"
#define wwwww_tag_wwwww_ALERT_MSG_SAVE_ACCOUNT_AND_PASSWORD_TO_PHOTO_FAIL        @"ALERT_MSG_SAVE_ACCOUNT_AND_PASSWORD_TO_PHOTO_FAIL"  //@"ALERT_MSG_SAVE_ACCOUNT_AND_PASSWORD_TO_PHOTO_FAIL"
#define wwwww_tag_wwwww_ALERT_MSG_SAVE_ACCOUNT_AND_PASSWORD_TO_PHOTO_SUCCESS        @"ALERT_MSG_SAVE_ACCOUNT_AND_PASSWORD_TO_PHOTO_SUCCESS"  //@"ALERT_MSG_SAVE_ACCOUNT_AND_PASSWORD_TO_PHOTO_SUCCESS"
#define wwwww_tag_wwwww_12        @"12"  //@"12"
#define wwwww_tag_wwwww_32        @"32"  //@"32"
#define wwwww_tag_wwwww_net_whatsapp_image        @"net.whatsapp.image"  //@"net.whatsapp.image"
#define wwwww_tag_wwwww_message        @"message"  //@"message"
#define wwwww_tag_wwwww_jp_naver_linecamera_pasteboard        @"jp.naver.linecamera.pasteboard"  //@"jp.naver.linecamera.pasteboard"
#define wwwww_tag_wwwww_public        @"public"  //@"public"
#define wwwww_tag_wwwww_png        @"png"  //@"png"
#define wwwww_tag_wwwww__CC_f4f4f5        @"#f4f4f5"  //@"#f4f4f5"
#define wwwww_tag_wwwww_mg        @"mg"  //@"mg"
#define wwwww_tag_wwwww_visitor        @"visitor"  //@"visitor"
#define wwwww_tag_wwwww_fb        @"fb"  //@"fb"
#define wwwww_tag_wwwww_google        @"google"  //@"google"
#define wwwww_tag_wwwww_twitter        @"twitter"  //@"twitter"
#define wwwww_tag_wwwww_naver        @"naver"  //@"naver"
#define wwwww_tag_wwwww_line        @"line"  //@"line"
#define wwwww_tag_wwwww_GamaAppleCurrentIdentifier        @"GamaAppleCurrentIdentifier"  //@"GamaAppleCurrentIdentifier"
#define wwwww_tag_wwwww_appleThirdID        @"appleThirdID"  //@"appleThirdID"
#define wwwww_tag_wwwww_appleToken        @"appleToken"  //@"appleToken"
#define wwwww_tag_wwwww_authorizationCode        @"authorizationCode"  //@"authorizationCode"
#define wwwww_tag_wwwww_appleVerfication        @"appleVerfication"  //@"appleVerfication"
#define wwwww_tag_wwwww_macrsmallenne_radi        @"授权信息均不符"  //@"授权信息均不符"
#define wwwww_tag_wwwww_follow_hibatic        @"授權信息均不符"  //@"授權信息均不符"
#define wwwww_tag_wwwww_GAMA_APPLE_DEAUTHORIZATION_FAILED_TEXT        @"GAMA_APPLE_DEAUTHORIZATION_FAILED_TEXT"  //@"GAMA_APPLE_DEAUTHORIZATION_FAILED_TEXT"
#define wwwww_tag_wwwww_GAMA_APPLE_AUTHRIZATION_REQUEST_FAILED_TEXT        @"GAMA_APPLE_AUTHRIZATION_REQUEST_FAILED_TEXT"  //@"GAMA_APPLE_AUTHRIZATION_REQUEST_FAILED_TEXT"
#define wwwww_tag_wwwww_GAMA_APPLE_AUTHRIZATION_INVALID        @"GAMA_APPLE_AUTHRIZATION_INVALID"  //@"GAMA_APPLE_AUTHRIZATION_INVALID"
#define wwwww_tag_wwwww_GAMA_APPLE_PROCESS_AUTHOROZATION_FAILED        @"GAMA_APPLE_PROCESS_AUTHOROZATION_FAILED"  //@"GAMA_APPLE_PROCESS_AUTHOROZATION_FAILED"
#define wwwww_tag_wwwww_GAMA_APPLE_RETURN_UNKNOWN_REASON        @"GAMA_APPLE_RETURN_UNKNOWN_REASON"  //@"GAMA_APPLE_RETURN_UNKNOWN_REASON"
#define wwwww_tag_wwwww_GamaCurrentIdentifier        @"GamaCurrentIdentifier"  //@"GamaCurrentIdentifier"
#define wwwww_tag_wwwww_ceptsive_primath        @"苹果授权凭证失效"  //@"苹果授权凭证失效"
#define wwwww_tag_wwwww_them_wife        @"苹果授权凭证状态良好"  //@"苹果授权凭证状态良好"
#define wwwww_tag_wwwww_hoplify_interary        @"未发现苹果授权凭证"  //@"未发现苹果授权凭证"
#define wwwww_tag_wwwww_successfulen_perical        @"SignInWithApple授权状态变化情况"  //@"SignInWithApple授权状态变化情况"
#define wwwww_tag_wwwww_GameswordAppleTmp        @"GameswordAppleTmp"  //@"GameswordAppleTmp"
#define wwwww_tag_wwwww_text_account_reg_success        @"text_account_reg_success"  //@"text_account_reg_success"
#define wwwww_tag_wwwww_py_login_success        @"py_login_success"  //@"py_login_success"
#define wwwww_tag_wwwww_fbOauthToken        @"fbOauthToken"  //@"fbOauthToken"
#define wwwww_tag_wwwww_googleIdToken        @"googleIdToken"  //@"googleIdToken"
#define wwwww_tag_wwwww_googleClientId        @"googleClientId"  //@"googleClientId"
#define wwwww_tag_wwwww_lineAccessToken        @"lineAccessToken"  //@"lineAccessToken"
#define wwwww_tag_wwwww_thirdAccessToken        @"thirdAccessToken"  //@"thirdAccessToken"
#define wwwww_tag_wwwww_text_account_bind_success        @"text_account_bind_success"  //@"text_account_bind_success"
#define wwwww_tag_wwwww_close        @"close"  //@"close"
#define wwwww_tag_wwwww_estimatedProgress        @"estimatedProgress"  //@"estimatedProgress"
#define wwwww_tag_wwwww_device_is_iPhoneX        @"device_is_iPhoneX"  //@"device_is_iPhoneX"
#define wwwww_tag_wwwww__CC_F13B11        @"#F13B11"  //@"#F13B11"
#define wwwww_tag_wwwww_viewDidLayoutSubviews        @"viewDidLayoutSubviews"  //@"viewDidLayoutSubviews"
#define wwwww_tag_wwwww_diplive_clinoful        @"提示"  //@"提示"
#define wwwww_tag_wwwww_matraeur_ampl        @"確定"  //@"確定"
#define wwwww_tag_wwwww_loading        @"loading"  //@"loading"
#define wwwww_tag_wwwww_title        @"title"  //@"title"
#define wwwww_tag_wwwww_URL        @"URL"  //@"URL"
#define wwwww_tag_wwwww_gama_prm_social_share_link        @"gama_prm_social_share_link"  //@"gama_prm_social_share_link"
#define wwwww_tag_wwwww_gama_prm_social_local_image        @"gama_prm_social_local_image"  //@"gama_prm_social_local_image"
#define wwwww_tag_wwwww_gama_prm_social_share_msg        @"gama_prm_social_share_msg"  //@"gama_prm_social_share_msg"
#define wwwww_tag_wwwww_gama_prm_social_invite_userId        @"gama_prm_social_invite_userId"  //@"gama_prm_social_invite_userId"
#define wwwww_tag_wwwww_gama_prm_social_invite_msg        @"gama_prm_social_invite_msg"  //@"gama_prm_social_invite_msg"
#define wwwww_tag_wwwww_gama_prm_social_invite_title        @"gama_prm_social_invite_title"  //@"gama_prm_social_invite_title"
#define wwwww_tag_wwwww_gama_prm_social_fields_content        @"gama_prm_social_fields_content"  //@"gama_prm_social_fields_content"
#define wwwww_tag_wwwww_text        @"text"  //@"text"
#define wwwww_tag_wwwww_text_select_phone_area_title        @"text_select_phone_area_title"  //@"text_select_phone_area_title"
#define wwwww_tag_wwwww_value        @"value"  //@"value"
#define wwwww_tag_wwwww_key        @"key"  //@"key"
#define wwwww_tag_wwwww_pattern        @"pattern"  //@"pattern"
#define wwwww_tag_wwwww_text_cancel        @"text_cancel"  //@"text_cancel"
#define wwwww_tag_wwwww_Key_AccountModelArray        @"Key_AccountModelArray"  //@"Key_AccountModelArray"
#define wwwww_tag_wwwww_SDK_LOGIN_TYPE        @"SDK_LOGIN_TYPE"  //@"SDK_LOGIN_TYPE"
#define wwwww_tag_wwwww_yes        @"yes"  //@"yes"
#define wwwww_tag_wwwww_radio_tenyesator        @"结束所有apple未消耗订单"  //@"结束所有apple未消耗订单"
#define wwwww_tag_wwwww_gasad_archi        @"apple没有历史未消耗订单"  //@"apple没有历史未消耗订单"
#define wwwww_tag_wwwww_didRoot        @"didRoot"  //@"didRoot"
#define wwwww_tag_wwwww_marketly_umbrern        @"越狱手机不支持内购"  //@"越狱手机不支持内购"
#define wwwww_tag_wwwww_yourselfenne_pent        @"监听AppStore支付状态"  //@"监听AppStore支付状态"
#define wwwww_tag_wwwww_listenaneous_lacrimaskatic        @"已经购买过商品"  //@"已经购买过商品"
#define wwwww_tag_wwwww_court_hundredlet        @"最终状态未确定"  //@"最终状态未确定"
#define wwwww_tag_wwwww_no        @"no"  //@"no"
#define wwwww_tag_wwwww_no_2        @"no_2"  //@"no_2"
#define wwwww_tag_wwwww_no_3        @"no_3"  //@"no_3"
#define wwwww_tag_wwwww_roboracity_starety        @"dealloc视图被销毁"  //@"dealloc视图被销毁"
#define wwwww_tag_wwwww_viewDidLoad        @"viewDidLoad"  //@"viewDidLoad"
#define wwwww_tag_wwwww_viewDidAppear        @"viewDidAppear"  //@"viewDidAppear"
#define wwwww_tag_wwwww_viewWillAppear        @"viewWillAppear"  //@"viewWillAppear"
#define wwwww_tag_wwwww_viewWillDisappear        @"viewWillDisappear"  //@"viewWillDisappear"
#define wwwww_tag_wwwww_viewDidDisappear        @"viewDidDisappear"  //@"viewDidDisappear"
#define wwwww_tag_wwwww_keyboardWillShow        @"keyboardWillShow"  //@"keyboardWillShow"
#define wwwww_tag_wwwww_keyboardWillHide        @"keyboardWillHide"  //@"keyboardWillHide"
#define wwwww_tag_wwwww_textFieldShouldReturn        @"textFieldShouldReturn"  //@"textFieldShouldReturn"
#define wwwww_tag_wwwww_textFieldShouldBeginEditing        @"textFieldShouldBeginEditing"  //@"textFieldShouldBeginEditing"
#define wwwww_tag_wwwww_textFieldShouldEndEditing        @"textFieldShouldEndEditing"  //@"textFieldShouldEndEditing"
#define wwwww_tag_wwwww_textFieldDidBeginEditing        @"textFieldDidBeginEditing"  //@"textFieldDidBeginEditing"
#define wwwww_tag_wwwww_textFieldDidEndEditing        @"textFieldDidEndEditing"  //@"textFieldDidEndEditing"
#define wwwww_tag_wwwww__CC_FF892E        @"#FF892E"  //@"#FF892E"
#define wwwww_tag_wwwww__CC_4CADFE        @"#4CADFE"  //@"#4CADFE"
#define wwwww_tag_wwwww__CC_02EDFC        @"#02EDFC"  //@"#02EDFC"
#define wwwww_tag_wwwww__CC_03CAFC        @"#03CAFC"  //@"#03CAFC"
#define wwwww_tag_wwwww__CC_90FD9E        @"#90FD9E"  //@"#90FD9E"
#define wwwww_tag_wwwww__CC_00C9FE        @"#00C9FE"  //@"#00C9FE"
#define wwwww_tag_wwwww_btn_hy_png        @"btn_hy.png"  //@"btn_hy.png"
#define wwwww_tag_wwwww_sdk_btn_bg_png        @"sdk_btn_bg.png"  //@"sdk_btn_bg.png"
#define wwwww_tag_wwwww_beautifulaire_sisterary        @"會員賬號登入"  //@"會員賬號登入"
#define wwwww_tag_wwwww_btn_fb_png        @"btn_fb.png"  //@"btn_fb.png"
#define wwwww_tag_wwwww_btn_yk_png        @"btn_yk.png"  //@"btn_yk.png"
#define wwwww_tag_wwwww_btn_ios_png        @"btn_ios.png"  //@"btn_ios.png"
#define wwwww_tag_wwwww_fatu_misless        @"會員登入"  //@"會員登入"
#define wwwww_tag_wwwww_nattion_pecc        @"註冊會員"  //@"註冊會員"
#define wwwww_tag_wwwww_sdk_btn_bdfb_png        @"sdk_btn_bdfb.png"  //@"sdk_btn_bdfb.png"
#define wwwww_tag_wwwww_sdk_btn_bdios_png        @"sdk_btn_bdios.png"  //@"sdk_btn_bdios.png"
#define wwwww_tag_wwwww_sdk_btn_bdyk_png        @"sdk_btn_bdyk.png"  //@"sdk_btn_bdyk.png"
#define wwwww_tag_wwwww_sexfy_egorary        @"切換帳號"  //@"切換帳號"
#define wwwww_tag_wwwww_thusence_discussion        @"綁定會員"  //@"綁定會員"
#define wwwww_tag_wwwww_ff3a3b        @"ff3a3b"  //@"ff3a3b"
#define wwwww_tag_wwwww_text_login        @"text_login"  //@"text_login"
#define wwwww_tag_wwwww_text_register        @"text_register"  //@"text_register"
#define wwwww_tag_wwwww_kLoginTabActTag        @"kLoginTabActTag"  //@"kLoginTabActTag"
#define wwwww_tag_wwwww_kRegTabActTag        @"kRegTabActTag"  //@"kRegTabActTag"
#define wwwww_tag_wwwww__CC_848484        @"#848484"  //@"#848484"
#define wwwww_tag_wwwww__CC_F23B12        @"#F23B12"  //@"#F23B12"
#define wwwww_tag_wwwww_text_title_notice        @"text_title_notice"  //@"text_title_notice"
#define wwwww_tag_wwwww__CC_E4E4E4        @"#E4E4E4"  //@"#E4E4E4"
#define wwwww_tag_wwwww__CC_DEDEDE        @"#DEDEDE"  //@"#DEDEDE"
#define wwwww_tag_wwwww_rememberTermsLableTapped        @"rememberTermsLableTapped"  //@"rememberTermsLableTapped"
#define wwwww_tag_wwwww_guest_login_btn        @"guest_login_btn"  //@"guest_login_btn"
#define wwwww_tag_wwwww_tips_have_account        @"tips_have_account"  //@"tips_have_account"
#define wwwww_tag_wwwww_text_login_other        @"text_login_other"  //@"text_login_other"
#define wwwww_tag_wwwww__CC_C0C0C0        @"#C0C0C0"  //@"#C0C0C0"
#define wwwww_tag_wwwww_text_ui_term_port_read2        @"text_ui_term_port_read2"  //@"text_ui_term_port_read2"
#define wwwww_tag_wwwww_sdk_terms_title        @"sdk_terms_title"  //@"sdk_terms_title"
#define wwwww_tag_wwwww_text_personal_clause_and_privacy_policy     @"text_personal_clause_and_privacy_policy"  //@"text_personal_clause_and_privacy_policy"
#define wwwww_tag_wwwww_kAgreeTermsCheckBoxBtnTag        @"kAgreeTermsCheckBoxBtnTag"  //@"kAgreeTermsCheckBoxBtnTag"
#define wwwww_tag_wwwww_appleLoginActTag        @"appleLoginActTag"  //@"appleLoginActTag"
#define wwwww_tag_wwwww_guestLoginActTag        @"guestLoginActTag"  //@"guestLoginActTag"
#define wwwww_tag_wwwww_fbLoginActTag        @"fbLoginActTag"  //@"fbLoginActTag"
#define wwwww_tag_wwwww_googleLoginActTag        @"googleLoginActTag"  //@"googleLoginActTag"
#define wwwww_tag_wwwww_lineLoginActTag        @"lineLoginActTag"  //@"lineLoginActTag"
#define wwwww_tag_wwwww_text_term_not_read        @"text_term_not_read"  //@"text_term_not_read"
#define wwwww_tag_wwwww_text_delete_account_tips        @"text_delete_account_tips"  //@"text_delete_account_tips"
#define wwwww_tag_wwwww_text_confire        @"text_confire"  //@"text_confire"
#define wwwww_tag_wwwww_text_delete_account        @"text_delete_account"  //@"text_delete_account"
#define wwwww_tag_wwwww_text_account_not_login        @"text_account_not_login"  //@"text_account_not_login"
#define wwwww_tag_wwwww_text_phone_bind        @"text_phone_bind"  //@"text_phone_bind"
#define wwwww_tag_wwwww__CC_2A2A2A        @"#2A2A2A"  //@"#2A2A2A"
#define wwwww_tag_wwwww__CC_606060        @"#606060"  //@"#606060"
#define wwwww_tag_wwwww_text_area_code        @"text_area_code"  //@"text_area_code"
#define wwwww_tag_wwwww_text_please_input_phone        @"text_please_input_phone"  //@"text_please_input_phone"
#define wwwww_tag_wwwww__CC_B8B8B8        @"#B8B8B8"  //@"#B8B8B8"
#define wwwww_tag_wwwww_text_get_vfcode        @"text_get_vfcode"  //@"text_get_vfcode"
#define wwwww_tag_wwwww_py_confire        @"py_confire"  //@"py_confire"
#define wwwww_tag_wwwww_text_has_phone_bind_tips        @"text_has_phone_bind_tips"  //@"text_has_phone_bind_tips"
#define wwwww_tag_wwwww__CC_4B4B4B        @"#4B4B4B"  //@"#4B4B4B"
#define wwwww_tag_wwwww_text_forgot_pwd        @"text_forgot_pwd"  //@"text_forgot_pwd"
#define wwwww_tag_wwwww_kGetVfCodeActTag        @"kGetVfCodeActTag"  //@"kGetVfCodeActTag"
#define wwwww_tag_wwwww_kOkActTag        @"kOkActTag"  //@"kOkActTag"
#define wwwww_tag_wwwww_py_vfcode_empty        @"py_vfcode_empty"  //@"py_vfcode_empty"
#define wwwww_tag_wwwww_text_pwd_not_equel        @"text_pwd_not_equel"  //@"text_pwd_not_equel"
#define wwwww_tag_wwwww_4        @"4"  //@"4"
#define wwwww_tag_wwwww_text_account_change_pwd_success        @"text_account_change_pwd_success"  //@"text_account_change_pwd_success"
#define wwwww_tag_wwwww_text_send_vf_code_success        @"text_send_vf_code_success"  //@"text_send_vf_code_success"
#define wwwww_tag_wwwww_text_reg_tips        @"text_reg_tips"  //@"text_reg_tips"
#define wwwww_tag_wwwww_cipitite_stateain        @"獲取驗證碼"  //@"獲取驗證碼"
#define wwwww_tag_wwwww__CC_ff3e37        @"#ff3e37"  //@"#ff3e37"
#define wwwww_tag_wwwww_text_confire_reg        @"text_confire_reg"  //@"text_confire_reg"
#define wwwww_tag_wwwww_quintial_determineie        @"同一手機當日不得收取驗證碼超過五次"  //@"同一手機當日不得收取驗證碼超過五次"
#define wwwww_tag_wwwww__CC_FF3E37        @"#FF3E37"  //@"#FF3E37"
#define wwwww_tag_wwwww_BTN_TITLE_BIND_ACCOUNT        @"BTN_TITLE_BIND_ACCOUNT"  //@"BTN_TITLE_BIND_ACCOUNT"
#define wwwww_tag_wwwww_btn_bind_account_png        @"btn_bind_account.png"  //@"btn_bind_account.png"
#define wwwww_tag_wwwww_GAMA_REGISTER_BIND_CONFIRM_TEXT        @"GAMA_REGISTER_BIND_CONFIRM_TEXT"  //@"GAMA_REGISTER_BIND_CONFIRM_TEXT"
#define wwwww_tag_wwwww_kRegisterAccountActTag        @"kRegisterAccountActTag"  //@"kRegisterAccountActTag"
#define wwwww_tag_wwwww_text_input_account        @"text_input_account"  //@"text_input_account"
#define wwwww_tag_wwwww_text_input_pwd        @"text_input_pwd"  //@"text_input_pwd"
#define wwwww_tag_wwwww_py_findpwd        @"py_findpwd"  //@"py_findpwd"
#define wwwww_tag_wwwww_kFindPwdActTag        @"kFindPwdActTag"  //@"kFindPwdActTag"
#define wwwww_tag_wwwww_kBackBtnActTag        @"kBackBtnActTag"  //@"kBackBtnActTag"
#define wwwww_tag_wwwww_kAccountLoginActTag        @"kAccountLoginActTag"  //@"kAccountLoginActTag"
#define wwwww_tag_wwwww_kSureDeleteAccountActTag        @"kSureDeleteAccountActTag"  //@"kSureDeleteAccountActTag"
#define wwwww_tag_wwwww_kCancelDeleteAccountActTag        @"kCancelDeleteAccountActTag"  //@"kCancelDeleteAccountActTag"
#define wwwww_tag_wwwww_text_free_register        @"text_free_register"  //@"text_free_register"
#define wwwww_tag_wwwww_sdk_provisions_first_enble        @"sdk_provisions_first_enble"  //@"sdk_provisions_first_enble"
#define wwwww_tag_wwwww_text_close        @"text_close"  //@"text_close"
#define wwwww_tag_wwwww_text_agree_read_tips        @"text_agree_read_tips"  //@"text_agree_read_tips"
#define wwwww_tag_wwwww__CC_545454        @"#545454"  //@"#545454"
#define wwwww_tag_wwwww_text_update_account        @"text_update_account"  //@"text_update_account"
#define wwwww_tag_wwwww_text_bind_account_tips        @"text_bind_account_tips"  //@"text_bind_account_tips"
#define wwwww_tag_wwwww_text_confire_update        @"text_confire_update"  //@"text_confire_update"
#define wwwww_tag_wwwww_text_has_bind_tips_mw        @"text_has_bind_tips_mw"  //@"text_has_bind_tips_mw"
#define wwwww_tag_wwwww_text_has_bind_tips_fb        @"text_has_bind_tips_fb"  //@"text_has_bind_tips_fb"
#define wwwww_tag_wwwww_text_has_bind_tips_google        @"text_has_bind_tips_google"  //@"text_has_bind_tips_google"
#define wwwww_tag_wwwww_text_has_bind_tips_guest        @"text_has_bind_tips_guest"  //@"text_has_bind_tips_guest"
#define wwwww_tag_wwwww_text_has_bind_tips_apple        @"text_has_bind_tips_apple"  //@"text_has_bind_tips_apple"
#define wwwww_tag_wwwww_text_has_bind_tips_line        @"text_has_bind_tips_line"  //@"text_has_bind_tips_line"
#define wwwww_tag_wwwww_text_has_upgrade_account        @"text_has_upgrade_account"  //@"text_has_upgrade_account"
#define wwwww_tag_wwwww_drawRect        @"drawRect"  //@"drawRect"
#define wwwww_tag_wwwww__CC_F94925        @"#F94925"  //@"#F94925"
#define wwwww_tag_wwwww_archae_effortfold        @"遊客登入"  //@"遊客登入"
#define wwwww_tag_wwwww_vigenast_claimistic        @"登入"  //@"登入"
#define wwwww_tag_wwwww__CC_EB2E2B        @"#EB2E2B"  //@"#EB2E2B"
#define wwwww_tag_wwwww_mostery_tricesimreachory        @"其他登入"  //@"其他登入"
#define wwwww_tag_wwwww_gama_ui_term_port_read2        @"gama_ui_term_port_read2"  //@"gama_ui_term_port_read2"
#define wwwww_tag_wwwww_sureenne_terless        @"綁定會員帳號"  //@"綁定會員帳號"
#define wwwww_tag_wwwww_plasative_comdebateatic        @"Apple帳號綁定"  //@"Apple帳號綁定"
#define wwwww_tag_wwwww_appleViewTapped        @"appleViewTapped"  //@"appleViewTapped"
#define wwwww_tag_wwwww_kBindAppleActTag        @"kBindAppleActTag"  //@"kBindAppleActTag"
#define wwwww_tag_wwwww_GAMA_APPLE_SYSTEM_OLD_WARNING        @"GAMA_APPLE_SYSTEM_OLD_WARNING"  //@"GAMA_APPLE_SYSTEM_OLD_WARNING"
#define wwwww_tag_wwwww_kBindFBActTag        @"kBindFBActTag"  //@"kBindFBActTag"
#define wwwww_tag_wwwww_kBindGuestActTag        @"kBindGuestActTag"  //@"kBindGuestActTag"
#define wwwww_tag_wwwww_text_change_pwd        @"text_change_pwd"  //@"text_change_pwd"
#define wwwww_tag_wwwww_text_confire_change        @"text_confire_change"  //@"text_confire_change"
#define wwwww_tag_wwwww_text_welcome_back        @"text_welcome_back"  //@"text_welcome_back"
#define wwwww_tag_wwwww_nend_update_account_bg        @"nend_update_account_bg"  //@"nend_update_account_bg"
#define wwwww_tag_wwwww_text_go_game        @"text_go_game"  //@"text_go_game"
#define wwwww_tag_wwwww_text_switch_account        @"text_switch_account"  //@"text_switch_account"
#define wwwww_tag_wwwww_text_update_account_bind        @"text_update_account_bind"  //@"text_update_account_bind"
#define wwwww_tag_wwwww_setViewStatue        @"setViewStatue"  //@"setViewStatue"
#define wwwww_tag_wwwww_py_login_page_change_pwd        @"py_login_page_change_pwd"  //@"py_login_page_change_pwd"
#define wwwww_tag_wwwww_kBindAccountActTag        @"kBindAccountActTag"  //@"kBindAccountActTag"
#define wwwww_tag_wwwww_kChangePwdActTag        @"kChangePwdActTag"  //@"kChangePwdActTag"
#define wwwww_tag_wwwww_kGoGameActTag        @"kGoGameActTag"  //@"kGoGameActTag"
#define wwwww_tag_wwwww_kSwitchAccountActTag        @"kSwitchAccountActTag"  //@"kSwitchAccountActTag"
#define wwwww_tag_wwwww_erraneous_styleward        @"確認註冊"  //@"確認註冊"
#define wwwww_tag_wwwww_fl_sdk_logo        @"fl_sdk_logo"  //@"fl_sdk_logo"
#define wwwww_tag_wwwww_sdk_btn_back_png        @"sdk_btn_back.png"  //@"sdk_btn_back.png"
#define wwwww_tag_wwwww_heurice_lithtoo        @"註冊"  //@"註冊"
#define wwwww_tag_wwwww_GAMA_PROVISIONS_PROTRAIT_TEXT        @"GAMA_PROVISIONS_PROTRAIT_TEXT"  //@"GAMA_PROVISIONS_PROTRAIT_TEXT"
#define wwwww_tag_wwwww_btn_checkbox_uncheck_png        @"btn_checkbox_uncheck.png"  //@"btn_checkbox_uncheck.png"
#define wwwww_tag_wwwww_fl_sdk_dx_png        @"fl_sdk_dx.png"  //@"fl_sdk_dx.png"
#define wwwww_tag_wwwww_soonoon_teleoator        @"驗證碼"  //@"驗證碼"
#define wwwww_tag_wwwww_corticoaster_numberature        @"請輸入驗證碼"  //@"請輸入驗證碼"
#define wwwww_tag_wwwww_broncheer_whitester        @"帳號"  //@"帳號"
#define wwwww_tag_wwwww_oursure_pleging        @"請輸入您的常用信箱"  //@"請輸入您的常用信箱"
#define wwwww_tag_wwwww_almostive_penotic        @"密碼"  //@"密碼"
#define wwwww_tag_wwwww_zyment_gamid        @"確認新密碼"  //@"確認新密碼"
#define wwwww_tag_wwwww_scientist_misceair        @"請輸入新密碼"  //@"請輸入新密碼"
#define wwwww_tag_wwwww_TXT_PH_ACCOUNT_INPUT_PWD_NEW        @"TXT_PH_ACCOUNT_INPUT_PWD_NEW"  //@"TXT_PH_ACCOUNT_INPUT_PWD_NEW"
#define wwwww_tag_wwwww_fontmentionry_labor        @"輸入舊密碼"  //@"輸入舊密碼"
#define wwwww_tag_wwwww_TXT_PH_ACCOUNT_INPUT_PWD_OLD        @"TXT_PH_ACCOUNT_INPUT_PWD_OLD"  //@"TXT_PH_ACCOUNT_INPUT_PWD_OLD"
#define wwwww_tag_wwwww_py_register_account_hit        @"py_register_account_hit"  //@"py_register_account_hit"
#define wwwww_tag_wwwww_py_register_password_hit        @"py_register_password_hit"  //@"py_register_password_hit"
#define wwwww_tag_wwwww_text_input_new_pwd_confire        @"text_input_new_pwd_confire"  //@"text_input_new_pwd_confire"
#define wwwww_tag_wwwww_text_input_new_pwd        @"text_input_new_pwd"  //@"text_input_new_pwd"
#define wwwww_tag_wwwww_py_input_old_password        @"py_input_old_password"  //@"py_input_old_password"
#define wwwww_tag_wwwww_lubricite_nearaceous        @"任何字符串"  //@"任何字符串"
#define wwwww_tag_wwwww__CC_3D5C9A        @"#3D5C9A"  //@"#3D5C9A"
#define wwwww_tag_wwwww_sdk_btn_fb_bg_png        @"sdk_btn_fb_bg.png"  //@"sdk_btn_fb_bg.png"
#define wwwww_tag_wwwww_fl_logo_png        @"fl_logo.png"  //@"fl_logo.png"
#define wwwww_tag_wwwww_today_fiveess        @"會員帳號登入"  //@"會員帳號登入"
#define wwwww_tag_wwwww_sdk_btn_icon_fb_png        @"sdk_btn_icon_fb.png"  //@"sdk_btn_icon_fb.png"
#define wwwww_tag_wwwww_sdk_btn_icon_apple_png        @"sdk_btn_icon_apple.png"  //@"sdk_btn_icon_apple.png"
#define wwwww_tag_wwwww_sdk_btn_icon_guest_png        @"sdk_btn_icon_guest.png"  //@"sdk_btn_icon_guest.png"
#define wwwww_tag_wwwww_betteritive_exampleage        @"遊客帳號登入"  //@"遊客帳號登入"
#define wwwww_tag_wwwww_ichthyshootness_stear        @"Facebook帳號綁定"  //@"Facebook帳號綁定"
#define wwwww_tag_wwwww_battbetter_aloneics        @"遊客帳號綁定"  //@"遊客帳號綁定"
#define wwwww_tag_wwwww_fl_sdk_mb_png        @"fl_sdk_mb.png"  //@"fl_sdk_mb.png"
#define wwwww_tag_wwwww_purgresponseism_polship        @"電話"  //@"電話"
#define wwwww_tag_wwwww_886        @"886"  //@"886"
#define wwwww_tag_wwwww_anything_scanslike        @"請輸入電話號碼"  //@"請輸入電話號碼"
#define wwwww_tag_wwwww__CC_A0A0A0        @"#A0A0A0"  //@"#A0A0A0"
#define wwwww_tag_wwwww_touchesBegan___        @"touchesBegan..."  //@"touchesBegan..."

#define wwwww_tag_wwwww__CC_FC676F      @"#FC676F"  //@"#FC676F"
#define wwwww_tag_wwwww__CC_FF9944      @"#FF9944"  //@"#FF9944"

#define wwwww_tag_wwwww_Upgrade_Account      @"Upgrade_Account"  //@"Upgrade_Account"
#define wwwww_tag_wwwww_Key_GameUserMode        @"Key_GameUserMode"  //@"Key_GameUserMode"
#define wwwww_tag_wwwww_Initiate_Checkout       @"Initiate_Checkout"  //@"Initiate_Checkout"

//#define wwwww_tag_wwwww_text_age_is14        @"text_age_is14"  //@"text_age_is14"
//#define wwwww_tag_wwwww_text_age_not14_logout        @"text_age_not14_logout"  //@"text_age_not14_logout"
//#define wwwww_tag_wwwww_text_age_already_14        @"text_age_already_14"  //@"text_age_already_14"
#define wwwww_tag_wwwww__CC_FF0000        @"#FF0000"  //@"#FF0000"
#define wwwww_tag_wwwww_text_privacy_policy        @"text_privacy_policy"  //@"text_privacy_policy"
#define wwwww_tag_wwwww_text_personal_clause        @"text_personal_clause"  //@"text_personal_clause"
#define wwwww_tag_wwwww_text_customer               @"text_customer"    //@"text_customer"

#define wwwww_tag_wwwww_purchase_over4          @"purchase_over4"   //@"purchase_over4"
#define wwwww_tag_wwwww_layout          @"layout"   //@"layout"
#define wwwww_tag_wwwww_text_select_pay_channel     @"text_select_pay_channel"   //@"text_select_pay_channel"
#define wwwww_tag_wwwww_text_pay_pay     @"text_pay_pay"   //@"text_pay_pay"
#define wwwww_tag_wwwww_onPayFinish      @"onPayFinish"   //@"onPayFinish"
#define wwwww_tag_wwwww_select_apple      @"select_apple"   //@"select_apple"
#define wwwww_tag_wwwww_select_other      @"select_other"   //@"select_other"
#define wwwww_tag_wwwww_trackEvent      @"trackEvent"   //@"trackEvent"
#define wwwww_tag_wwwww_openSysBrowser      @"openSysBrowser"   //@"openSysBrowser"
#define wwwww_tag_wwwww_text_waiting         @"text_waiting" //@"text_waiting"
#define wwwww_tag_wwwww_text_change_account       @"text_change_account" //@"text_change_account"


//new
#define wwwww_tag_wwwww_adjust_app_token        @"adjust_app_token"  //@"adjust_app_token"
#define wwwww_tag_wwwww_oceer_ratherfold        @"{YourAppToken}"  //@"{YourAppToken}"
#define wwwww_tag_wwwww_adjustAppToken_is_empty        @"adjustAppToken is empty"  //@"adjustAppToken is empty"
#define wwwww_tag_wwwww_adjustAppToken_init_finish        @"adjustAppToken init finish"  //@"adjustAppToken init finish"
#define wwwww_tag_wwwww_ratherarian_vickin        @"adjust track event start eventName=%@"  //@"adjust track event start eventName=%@"
#define wwwww_tag_wwwww_encephalo_racewise        @"adjust-info-%@"  //@"adjust-info-%@"
#define wwwww_tag_wwwww_health_hierlike        @"adjust track event adjust-info-xxx file is empty, name=%@"  //@"adjust track event adjust-info-xxx file is empty, name=%@"
#define wwwww_tag_wwwww_evenacy_mentionistic        @"adjust track event eventToken is empty, eventName=%@"  //@"adjust track event eventToken is empty, eventName=%@"
#define wwwww_tag_wwwww_postulative_archier        @"adjust track event finish, eventName=%@"  //@"adjust track event finish, eventName=%@"
#define wwwww_tag_wwwww_hysterfier_throughouty        @"%@_%@"  //@"%@_%@"
#define wwwww_tag_wwwww_purposeon_commercialsive        @"log event exist, eventName=%@"  //@"log event exist, eventName=%@"
#define wwwww_tag_wwwww_notopatientacity_sperm        @"log event, eventName=%@"  //@"log event, eventName=%@"
#define wwwww_tag_wwwww_purchase_hf        @"purchase_hf"  //@"purchase_hf"
#define wwwww_tag_wwwww_purchase_first_charge_hf        @"purchase_first_charge_hf"  //@"purchase_first_charge_hf"
#define wwwww_tag_wwwww_purchase_99_single_hf        @"purchase_99_single_hf"  //@"purchase_99_single_hf"
#define wwwww_tag_wwwww_continuous_50_dollars_recharege_hf        @"continuous_50_dollars_recharege_hf"  //@"continuous_50_dollars_recharege_hf"
#define wwwww_tag_wwwww_continuous_100_dollars_recharege_hf        @"continuous_100_dollars_recharege_hf"  //@"continuous_100_dollars_recharege_hf"
#define wwwww_tag_wwwww_continuous_500_dollars_recharege_hf        @"continuous_500_dollars_recharege_hf"  //@"continuous_500_dollars_recharege_hf"
#define wwwww_tag_wwwww_continuous_1000_dollars_recharege_hf        @"continuous_1000_dollars_recharege_hf"  //@"continuous_1000_dollars_recharege_hf"
#define wwwww_tag_wwwww_continuous_3000_dollars_recharege_hf        @"continuous_3000_dollars_recharege_hf"  //@"continuous_3000_dollars_recharege_hf"
#define wwwww_tag_wwwww_purchase_2rd_charge_hf        @"purchase_2rd_charge_hf"  //@"purchase_2rd_charge_hf"
#define wwwww_tag_wwwww_purchase_3rd_charge_hf        @"purchase_3rd_charge_hf"  //@"purchase_3rd_charge_hf"
#define wwwww_tag_wwwww_purchase_10rd_charge_hf        @"purchase_10rd_charge_hf"  //@"purchase_10rd_charge_hf"
#define wwwww_tag_wwwww_pungic_vulgindeeder        @"send event to sever exist, eventName=%@"  //@"send event to sever exist, eventName=%@"
#define wwwww_tag_wwwww_privify_volunttion        @"send event to sever, eventName=%@"  //@"send event to sever, eventName=%@"
#define wwwww_tag_wwwww_fishain_comacy        @"send event to sever success, eventName=%@"  //@"send event to sever success, eventName=%@"
#define wwwww_tag_wwwww_trus_oligo        @"afDevKey:%@,appId=%@"  //@"afDevKey:%@,appId=%@"
#define wwwww_tag_wwwww_precice_putenne        @"idfa=%@"  //@"idfa=%@"
#define wwwww_tag_wwwww_hortoon_nuptianeity        @"请在设置-隐私-跟踪中允许App请求跟踪"  //@"请在设置-隐私-跟踪中允许App请求跟踪"
#define wwwww_tag_wwwww_florium_notise        @"请在设置-隐私-广告中打开广告跟踪功能"  //@"请在设置-隐私-广告中打开广告跟踪功能"
#define wwwww_tag_wwwww_relationship_ostiist        @"logEventWithEventName=%@"  //@"logEventWithEventName=%@"
#define wwwww_tag_wwwww_quesitwindowence_tendaceous        @"logEventPurchaseValues af name=%@"  //@"logEventPurchaseValues af name=%@"
#define wwwww_tag_wwwww_blood_mic        @"logEventPurchaseValues firebase name=%@"  //@"logEventPurchaseValues firebase name=%@"
#define wwwww_tag_wwwww_logEventPurchaseValues_fb        @"logEventPurchaseValues fb"  //@"logEventPurchaseValues fb"
#define wwwww_tag_wwwww_usdPrice        @"usdPrice"  //@"usdPrice"
#define wwwww_tag_wwwww_currency        @"currency"  //@"currency"
#define wwwww_tag_wwwww_manthade_ableenne        @"Status: Authenticated:userID=%@,name=%@,email=%@,,idToken=%@,,accessToken=%@"  //@"Status: Authenticated:userID=%@,name=%@,email=%@,,idToken=%@,,accessToken=%@"
#define wwwww_tag_wwwww_Status__Not_authenticated        @"Status: Not authenticated"  //@"Status: Not authenticated"
#define wwwww_tag_wwwww_GIDDelegate_application_openURL_options        @"GIDDelegate application openURL options"  //@"GIDDelegate application openURL options"
#define wwwww_tag_wwwww_kClientID_is_empty        @"kClientID is empty"  //@"kClientID is empty"
#define wwwww_tag_wwwww_althoughatic_phono        @"google kClientID = %@"  //@"google kClientID = %@"
#define wwwww_tag_wwwww_agent_basivisitite        @"gid signInWithPresentingViewController error: %@"  //@"gid signInWithPresentingViewController error: %@"
#define wwwww_tag_wwwww_icosity_pungar        @"signInResult == nil"  //@"signInResult == nil"
#define wwwww_tag_wwwww_gamb_sign        @"Status: Failed to disconnect: %@"  //@"Status: Failed to disconnect: %@"
#define wwwww_tag_wwwww_Status__Disconnected        @"Status: Disconnected"  //@"Status: Disconnected"
#define wwwww_tag_wwwww_application_openURL_options        @"application openURL options"  //@"application openURL options"
#define wwwww_tag_wwwww_requestThirdpartyLogin        @"requestThirdpartyLogin"  //@"requestThirdpartyLogin"
#define wwwww_tag_wwwww_isValidAccessTokenExpireTimeNow_NO        @"isValidAccessTokenExpireTimeNow NO"  //@"isValidAccessTokenExpireTimeNow NO"
#define wwwww_tag_wwwww_https___openapi_naver_com_v1_nid_getUserProfile_xml        @"https://openapi.naver.com/v1/nid/getUserProfile.xml"  //@"https://openapi.naver.com/v1/nid/getUserProfile.xml"
#define wwwww_tag_wwwww_https___openapi_naver_com_v1_nid_me        @"https://openapi.naver.com/v1/nid/me"  //@"https://openapi.naver.com/v1/nid/me"
#define wwwww_tag_wwwww_getUserProfile        @"getUserProfile"  //@"getUserProfile"
#define wwwww_tag_wwwww_conferencean_growaneity        @"Bearer %@"  //@"Bearer %@"
#define wwwww_tag_wwwww_Authorization        @"Authorization"  //@"Authorization"
#define wwwww_tag_wwwww_octavarian_leaveless        @"Error happened - %@"  //@"Error happened - %@"
#define wwwww_tag_wwwww_querward_billics        @"recevied data - %@"  //@"recevied data - %@"
#define wwwww_tag_wwwww_resultcode        @"resultcode"  //@"resultcode"
#define wwwww_tag_wwwww_message        @"message"  //@"message"
#define wwwww_tag_wwwww_response        @"response"  //@"response"
#define wwwww_tag_wwwww_nickname        @"nickname"  //@"nickname"
#define wwwww_tag_wwwww_lith_nomful        @"%s=[%@]"  //@"%s=[%@]"
#define wwwww_tag_wwwww_phrynain_beginization        @"oauth20Connection didFailWithError %@"  //@"oauth20Connection didFailWithError %@"
#define wwwww_tag_wwwww_closeid_exoate        @"oauth20ConnectionDidFinishRequestACTokenWithAuthCode OAuth Success!\n\nAccess Token - %@\n\nAccess Token Expire Date- %@\n\nRefresh Token - %@"  //@"oauth20ConnectionDidFinishRequestACTokenWithAuthCode OAuth Success!\n\nAccess Token - %@\n\nAccess Token Expire Date- %@\n\nRefresh Token - %@"
#define wwwww_tag_wwwww_nice_themselvesit        @"oauth20ConnectionDidFinishRequestACTokenWithRefreshToken Refresh Success!\n\nAccess Token - %@\n\nAccess sToken ExpireDate- %@"  //@"oauth20ConnectionDidFinishRequestACTokenWithRefreshToken Refresh Success!\n\nAccess Token - %@\n\nAccess sToken ExpireDate- %@"
#define wwwww_tag_wwwww_oauth20ConnectionDidFinishDeleteToken        @"oauth20ConnectionDidFinishDeleteToken"  //@"oauth20ConnectionDidFinishDeleteToken"
#define wwwww_tag_wwwww_oscillitious_ducthrowid        @"oauth20Connection didFinishAuthorizationWithResult Getting auth code from NaverApp success!"  //@"oauth20Connection didFinishAuthorizationWithResult Getting auth code from NaverApp success!"
#define wwwww_tag_wwwww_volaform_uponity        @"oauth20Connection didFailAuthorizationWithReceiveType NaverApp login fail handler receiveType=%d"  //@"oauth20Connection didFailAuthorizationWithReceiveType NaverApp login fail handler receiveType=%d"
#define wwwww_tag_wwwww_application_openURL_sourceApplication_annotation        @"application openURL sourceApplication annotation"  //@"application openURL sourceApplication annotation"
#define wwwww_tag_wwwww_ornithoress_missast        @"ios9 and later = application openURL options，openURL:%@"  //@"ios9 and later = application openURL options，openURL:%@"
#define wwwww_tag_wwwww_UISupportedInterfaceOrientations        @"UISupportedInterfaceOrientations"  //@"UISupportedInterfaceOrientations"
#define wwwww_tag_wwwww_UIInterfaceOrientationPortrait        @"UIInterfaceOrientationPortrait"  //@"UIInterfaceOrientationPortrait"
#define wwwww_tag_wwwww_UIInterfaceOrientationPortraitUpsideDown        @"UIInterfaceOrientationPortraitUpsideDown"  //@"UIInterfaceOrientationPortraitUpsideDown"
#define wwwww_tag_wwwww_UIInterfaceOrientationLandscapeLeft        @"UIInterfaceOrientationLandscapeLeft"  //@"UIInterfaceOrientationLandscapeLeft"
#define wwwww_tag_wwwww_UIInterfaceOrientationLandscapeRight        @"UIInterfaceOrientationLandscapeRight"  //@"UIInterfaceOrientationLandscapeRight"
#define wwwww_tag_wwwww_ldy_sdk_1228        @"ldy-sdk-1228"  //@"ldy-sdk-1228"
#define wwwww_tag_wwwww_leonenne_pressure        @"SDK Version : %@"  //@"SDK Version : %@"
#define wwwww_tag_wwwww_sdkLoginWithHandler        @"sdkLoginWithHandler"  //@"sdkLoginWithHandler"
#define wwwww_tag_wwwww_currentThread_is_not_main_thread        @"currentThread is not main thread"  //@"currentThread is not main thread"
#define wwwww_tag_wwwww_switchLoginWithHandler        @"switchLoginWithHandler"  //@"switchLoginWithHandler"
#define wwwww_tag_wwwww_sdkLoginWithHandlerForInner        @"sdkLoginWithHandlerForInner"  //@"sdkLoginWithHandlerForInner"
#define wwwww_tag_wwwww_mensar_failier        @"[UIDevice currentDevice] systemVersion].intValue < 8"  //@"[UIDevice currentDevice] systemVersion].intValue < 8"
#define wwwww_tag_wwwww_controller_setModalPresentationStyle_UIModalPresentationOverCurrentContext        @"controller setModalPresentationStyle:UIModalPresentationOverCurrentContext"  //@"controller setModalPresentationStyle:UIModalPresentationOverCurrentContext"
#define wwwww_tag_wwwww_not_def___IPHONE_8_0        @"not def __IPHONE_8_0"  //@"not def __IPHONE_8_0"
#define wwwww_tag_wwwww_last_stultiarium        @"setRoleInfo角色信息：roleID = %@，roleName = %@，roleLevel = %@，roleVipLevel = %@，serverCode = %@，serverName = %@"  //@"setRoleInfo角色信息：roleID = %@，roleName = %@，roleLevel = %@，roleVipLevel = %@，serverCode = %@，serverName = %@"
#define wwwww_tag_wwwww_ceivite_sidersciencean        @"角色重要信息为空,请检查参数中 roleId roleName roleLevel serverCode是否有值"  //@"角色重要信息为空,请检查参数中 roleId roleName roleLevel serverCode是否有值"
#define wwwww_tag_wwwww_startMySdkPay___        @"startMySdkPay..."  //@"startMySdkPay..."
#define wwwww_tag_wwwww_sdk_other_ppp_url        @"sdk_other_ppp_url"  //@"sdk_other_ppp_url"
#define wwwww_tag_wwwww_dower_pollicitude        @"startMySdkPay myPayUrl=%@"  //@"startMySdkPay myPayUrl=%@"
#define wwwww_tag_wwwww_tainpage_lepid        @"exception:%@"  //@"exception:%@"
#define wwwww_tag_wwwww_MWWebViewController_presentViewController_completioN        @"MWWebViewController presentViewController completioN"  //@"MWWebViewController presentViewController completioN"
#define wwwww_tag_wwwww_startMySdkPay_open_end        @"startMySdkPay open end"  //@"startMySdkPay open end"
#define wwwww_tag_wwwww_bilient_loqui        @"储值接口传入的参数 ：roleId : %@ , serverCode : %@ , roleName : %@"  //@"储值接口传入的参数 ：roleId : %@ , serverCode : %@ , roleName : %@"
#define wwwww_tag_wwwww_fireuous_quasi        @"储值接口传入的参数 ：productid : %@ , cpOrderId : %@ , extra : %@"  //@"储值接口传入的参数 ：productid : %@ , cpOrderId : %@ , extra : %@"
#define wwwww_tag_wwwww_productId_must_be_not_empty        @"productId must be not empty"  //@"productId must be not empty"
#define wwwww_tag_wwwww_roleId_must_be_not_empty        @"roleId must be not empty"  //@"roleId must be not empty"
#define wwwww_tag_wwwww_serverCode_must_be_not_empty        @"serverCode must be not empty"  //@"serverCode must be not empty"
#define wwwww_tag_wwwww_cpOrderId_must_be_not_empty        @"cpOrderId must be not empty"  //@"cpOrderId must be not empty"
#define wwwww_tag_wwwww_agoy_beyondan        @"error:請重新登入遊戲進行充值"  //@"error:請重新登入遊戲進行充值"
#define wwwww_tag_wwwww_deal_veterose        @"用户登录信息不存在 currentAccountModel nil"  //@"用户登录信息不存在 currentAccountModel nil"
#define wwwww_tag_wwwww_plecfaction_tediunder        @"客服地址错误 csurl=%@"  //@"客服地址错误 csurl=%@"
#define wwwww_tag_wwwww_lievtic_managementice        @"客服地址csurl=%@"  //@"客服地址csurl=%@"
#define wwwww_tag_wwwww__CC_3EB2FF        @"#3EB2FF"  //@"#3EB2FF"
#define wwwww_tag_wwwww_eueer_cumbsion        @"客服地址open end"  //@"客服地址open end"
#define wwwww_tag_wwwww_line___        @"line://"  //@"line://"
#define wwwww_tag_wwwww_https___itunes_apple_com_app_line_id443904275        @"https://itunes.apple.com/app/line/id443904275"  //@"https://itunes.apple.com/app/line/id443904275"
#define wwwww_tag_wwwww_passeracity_answeric        @"line://msg/text/%@"  //@"line://msg/text/%@"
#define wwwww_tag_wwwww_Scheme_share_succeed        @"Scheme share succeed"  //@"Scheme share succeed"
#define wwwww_tag_wwwww_gression_decision        @"addLocalNotificationWithTitle 成功添加推送"  //@"addLocalNotificationWithTitle 成功添加推送"
#define wwwww_tag_wwwww_showActView        @"showActView"  //@"showActView"
#define wwwww_tag_wwwww_This_feature_is_not_turned_on        @"This feature is not turned on"  //@"This feature is not turned on"
#define wwwww_tag_wwwww_1_0_8        @"1.0.8"  //@"1.0.8"
#define wwwww_tag_wwwww_AFNetworkReachability_Not_Reachable        @"AFNetworkReachability Not Reachable"  //@"AFNetworkReachability Not Reachable"
#define wwwww_tag_wwwww_AFNetworkReachability_Reachable_via_WWAN        @"AFNetworkReachability Reachable via WWAN"  //@"AFNetworkReachability Reachable via WWAN"
#define wwwww_tag_wwwww_AFNetworkReachability_Reachable_via_WiFi        @"AFNetworkReachability Reachable via WiFi"  //@"AFNetworkReachability Reachable via WiFi"
#define wwwww_tag_wwwww_AFNetworkReachability_Unknown        @"AFNetworkReachability Unknown"  //@"AFNetworkReachability Unknown"
#define wwwww_tag_wwwww_dispatch_after_afnReachability_start        @"dispatch_after afnReachability start"  //@"dispatch_after afnReachability start"
#define wwwww_tag_wwwww_time_to_afnReachability_start        @"time to afnReachability start"  //@"time to afnReachability start"
#define wwwww_tag_wwwww_latafter_liveern        @"didReceiveRegistrationToken fcmToken = %@"  //@"didReceiveRegistrationToken fcmToken = %@"
#define wwwww_tag_wwwww_tra_hortative        @"FCM registration token: %@"  //@"FCM registration token: %@"
#define wwwww_tag_wwwww_tournious_migrist        @"willPresentNotification = %@"  //@"willPresentNotification = %@"
#define wwwww_tag_wwwww_ponddrawability_narrcentralette        @"Message ID: %@"  //@"Message ID: %@"
#define wwwww_tag_wwwww_amphfic_sacrship        @"push token:%@"  //@"push token:%@"
#define wwwww_tag_wwwww_registerUninstall_        @"registerUninstall:"  //@"registerUninstall:"
#define wwwww_tag_wwwww_setAPNSToken_        @"setAPNSToken:"  //@"setAPNSToken:"
#define wwwww_tag_wwwww_appDidReceiveMessage_        @"appDidReceiveMessage:"  //@"appDidReceiveMessage:"
#define wwwww_tag_wwwww_fb_login_isCancelled        @"fb login isCancelled"  //@"fb login isCancelled"
#define wwwww_tag_wwwww_fb_login_success        @"fb login success"  //@"fb login success"
#define wwwww_tag_wwwww_stanndaughtersion_organizationsion        @"fb login error:%@"  //@"fb login error:%@"
#define wwwww_tag_wwwww_provideory_pollicry        @"#%@"  //@"#%@"
#define wwwww_tag_wwwww_fbapi___        @"fbapi://"  //@"fbapi://"
#define wwwww_tag_wwwww_FBSDKShareDialogModeNative_not_ok        @"FBSDKShareDialogModeNative not ok"  //@"FBSDKShareDialogModeNative not ok"
#define wwwww_tag_wwwww_share_didCompleteWithResults        @"share didCompleteWithResults"  //@"share didCompleteWithResults"
#define wwwww_tag_wwwww_scrupar_cinctaster        @"share didFailWithError_MMMethodMMM: %@"  //@"share didFailWithError_MMMethodMMM: %@"
#define wwwww_tag_wwwww_af_complete_registration_hf        @"af_complete_registration_hf"  //@"af_complete_registration_hf"
#define wwwww_tag_wwwww_sign_up_hf        @"sign_up_hf"  //@"sign_up_hf"
#define wwwww_tag_wwwww_af_login_hf        @"af_login_hf"  //@"af_login_hf"
#define wwwww_tag_wwwww_login_hf        @"login_hf"  //@"login_hf"
#define wwwww_tag_wwwww_sign_up_account_hf        @"sign_up_account_hf"  //@"sign_up_account_hf"
#define wwwww_tag_wwwww_login_account_hf        @"login_account_hf"  //@"login_account_hf"
#define wwwww_tag_wwwww_sign_up_visitor_hf        @"sign_up_visitor_hf"  //@"sign_up_visitor_hf"
#define wwwww_tag_wwwww_login_visitor_hf        @"login_visitor_hf"  //@"login_visitor_hf"
#define wwwww_tag_wwwww_asant_shotot        @"yesterDate=%@, regDate=%@"  //@"yesterDate=%@, regDate=%@"
#define wwwww_tag_wwwww_log_event_Paid_D2Login_start        @"log event Paid_D2Login start"  //@"log event Paid_D2Login start"
#define wwwww_tag_wwwww_Paid_D2Login        @"Paid_D2Login"  //@"Paid_D2Login"
#define wwwww_tag_wwwww_complete_2nd_login_hf        @"complete_2nd_login_hf"  //@"complete_2nd_login_hf"
#define wwwww_tag_wwwww_complete_3nd_login_hf        @"complete_3nd_login_hf"  //@"complete_3nd_login_hf"
#define wwwww_tag_wwwww_complete_5nd_login_hf        @"complete_5nd_login_hf"  //@"complete_5nd_login_hf"
#define wwwww_tag_wwwww_complete_7nd_login_hf        @"complete_7nd_login_hf"  //@"complete_7nd_login_hf"
#define wwwww_tag_wwwww_not_device_is_iPhoneX        @"not device_is_iPhoneX"  //@"not device_is_iPhoneX"
#define wwwww_tag_wwwww_MWWebViewController_viewDidLoad        @"MWWebViewController viewDidLoad"  //@"MWWebViewController viewDidLoad"
#define wwwww_tag_wwwww_userContentController_dismissViewControllerAnimated        @"userContentController dismissViewControllerAnimated"  //@"userContentController dismissViewControllerAnimated"
#define wwwww_tag_wwwww_state_furc        @"页面开始加载 webView didStartProvisionalNavigation"  //@"页面开始加载 webView didStartProvisionalNavigation"
#define wwwww_tag_wwwww_word_fanior        @"页面加载失败时调用 webView didFailProvisionalNavigation"  //@"页面加载失败时调用 webView didFailProvisionalNavigation"
#define wwwww_tag_wwwww_avi_revealfier        @"页面开始返回webView didCommitNavigation"  //@"页面开始返回webView didCommitNavigation"
#define wwwww_tag_wwwww_awayency_nonelike        @"页面完成加载webView didFinishNavigation"  //@"页面完成加载webView didFinishNavigation"
#define wwwww_tag_wwwww_herbibility_largistic        @"提交发生错误时调 webView didFailNavigation withError"  //@"提交发生错误时调 webView didFailNavigation withError"
#define wwwww_tag_wwwww_parti_coldsure        @"决定是否跳转 webView decidePolicyForNavigationAction decisionHandler"  //@"决定是否跳转 webView decidePolicyForNavigationAction decisionHandler"
#define wwwww_tag_wwwww_sten_edgeian        @"收到服务器重定 didReceiveServerRedirectForProvisionalNavigation"  //@"收到服务器重定 didReceiveServerRedirectForProvisionalNavigation"
#define wwwww_tag_wwwww_pictoify_anyone        @"webView decidePolicyForNavigationResponse statusCode = %d"  //@"webView decidePolicyForNavigationResponse statusCode = %d"
#define wwwww_tag_wwwww_completionHandler_runJavaScriptAlertPanelWithMessage        @"completionHandler runJavaScriptAlertPanelWithMessage"  //@"completionHandler runJavaScriptAlertPanelWithMessage"
#define wwwww_tag_wwwww_completionHandler_createWebViewWithConfiguration_windowFeatures        @"completionHandler createWebViewWithConfiguration windowFeatures"  //@"completionHandler createWebViewWithConfiguration windowFeatures"
#define wwwww_tag_wwwww_gemperiodain_crepitical        @"userContentController message=%@"  //@"userContentController message=%@"
#define wwwww_tag_wwwww_shouldAutorotate        @"shouldAutorotate"  //@"shouldAutorotate"
#define wwwww_tag_wwwww_supportedInterfaceOrientations        @"supportedInterfaceOrientations"  //@"supportedInterfaceOrientations"
#define wwwww_tag_wwwww_preferredInterfaceOrientationForPresentation        @"preferredInterfaceOrientationForPresentation"  //@"preferredInterfaceOrientationForPresentation"
#define wwwww_tag_wwwww_MWWebViewController_releaseAll        @"MWWebViewController releaseAll"  //@"MWWebViewController releaseAll"
#define wwwww_tag_wwwww_MWWebViewController_dealloc        @"MWWebViewController dealloc"  //@"MWWebViewController dealloc"
#define wwwww_tag_wwwww_languagement_pludeathproof        @"\n[文件名:%s]\n"  //@"\n[文件名:%s]\n"
#define wwwww_tag_wwwww_shoulderarian_newspaperism        @"[输出:"  //@"[输出:"
#define wwwww_tag_wwwww_suf_wholehood        @"MW_SDK:%@"  //@"MW_SDK:%@"
#define wwwww_tag_wwwww_hoursive_scindile        @"MWSDK:%@"  //@"MWSDK:%@"
#define wwwww_tag_wwwww_bat_bacair        @"%@%@"  //@"%@%@"
#define wwwww_tag_wwwww_last_aesthetature        @"-%s-:%@"  //@"-%s-:%@"
#define wwwww_tag_wwwww_CFBundleName        @"CFBundleName"  //@"CFBundleName"
#define wwwww_tag_wwwww_CFBundleIdentifier        @"CFBundleIdentifier"  //@"CFBundleIdentifier"
#define wwwww_tag_wwwww_CFBundleShortVersionString        @"CFBundleShortVersionString"  //@"CFBundleShortVersionString"
#define wwwww_tag_wwwww_CFBundleVersion        @"CFBundleVersion"  //@"CFBundleVersion"
#define wwwww_tag_wwwww_CFBundleDisplayName        @"CFBundleDisplayName"  //@"CFBundleDisplayName"
#define wwwww_tag_wwwww_necrion_coelibility        @"%02x:%02x:%02x:%02x:%02x:%02x"  //@"%02x:%02x:%02x:%02x:%02x:%02x"
#define wwwww_tag_wwwww_vericollegeety_uran        @"Unable to obtain a key window, markingas keyWindow"  //@"Unable to obtain a key window, markingas keyWindow"
#define wwwww_tag_wwwww_manthemability_phildecide        @"topController nil,Unable to obtain topController"  //@"topController nil,Unable to obtain topController"
#define wwwww_tag_wwwww_Unable_to_find_a_valid_UIWindow        @"Unable to find a valid UIWindow"  //@"Unable to find a valid UIWindow"
#define wwwww_tag_wwwww_introkillety_hopeery        @" screen_frame:w%f_h%f"  //@" screen_frame:w%f_h%f"
#define wwwww_tag_wwwww_yyyy_MM_dd_HH_mm        @"yyyy-MM-dd_HH:mm"  //@"yyyy-MM-dd_HH:mm"
#define wwwww_tag_wwwww_yyyy_MM_dd_HH_mm_ss_SS        @"yyyy-MM-dd HH:mm:ss SS"  //@"yyyy-MM-dd HH:mm:ss SS"
#define wwwww_tag_wwwww_2023_12_20        @"2023-12-20"  //@"2023-12-20"
#define wwwww_tag_wwwww_2023_12_27        @"2023-12-27"  //@"2023-12-27"
#define wwwww_tag_wwwww_wishice_abilityeer        @"%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x"  //@"%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x"
#define wwwww_tag_wwwww_kCFLocaleCountryCodeKey        @"kCFLocaleCountryCodeKey"  //@"kCFLocaleCountryCodeKey"
#define wwwww_tag_wwwww_kCFLocaleLanguageCodeKey        @"kCFLocaleLanguageCodeKey"  //@"kCFLocaleLanguageCodeKey"
#define wwwww_tag_wwwww_card_micrlet        @" %@配置项缺少或错误，值应为：%@"  //@" %@配置项缺少或错误，值应为：%@"
#define wwwww_tag_wwwww_CFBundleURLTypes        @"CFBundleURLTypes"  //@"CFBundleURLTypes"
#define wwwww_tag_wwwww_CFBundleURLName        @"CFBundleURLName"  //@"CFBundleURLName"
#define wwwww_tag_wwwww_menoess_becomeitor        @" CFBundleURLName配置项缺少或错误，值应为：%@"  //@" CFBundleURLName配置项缺少或错误，值应为：%@"
#define wwwww_tag_wwwww_CFBundleURLSchemes        @"CFBundleURLSchemes"  //@"CFBundleURLSchemes"
#define wwwww_tag_wwwww_xenation_logy        @" CFBundleURLSchemes配置项缺少或错误，应包含：%@"  //@" CFBundleURLSchemes配置项缺少或错误，应包含：%@"
#define wwwww_tag_wwwww_PMture_leasteer        @"Info.plist文件配置不完整：%@%@%@；\n请同时参考SDK配置文档！"  //@"Info.plist文件配置不完整：%@%@%@；\n请同时参考SDK配置文档！"
#define wwwww_tag_wwwww__CC_C0C0C0        @"#C0C0C0"  //@"#C0C0C0"
#define wwwww_tag_wwwww__CC_777777        @"#777777"  //@"#777777"
#define wwwww_tag_wwwww_ventrization_asfic        @"action = %@"  //@"action = %@"
#define wwwww_tag_wwwww_DY_UID        @"DY_UID"  //@"DY_UID"
#define wwwww_tag_wwwww_Problem_deleting_current_dictionary_        @"Problem deleting current dictionary."  //@"Problem deleting current dictionary."
#define wwwww_tag_wwwww_liveel_impact        @"Serious error, no matching item found in the keychain.\n"  //@"Serious error, no matching item found in the keychain.\n"
#define wwwww_tag_wwwww_headate_thoughtard        @"Couldn't update the Keychain Item."  //@"Couldn't update the Keychain Item."
#define wwwww_tag_wwwww_eye_dinner        @"Updating the Keychain Item. result: %d"  //@"Updating the Keychain Item. result: %d"
#define wwwww_tag_wwwww_archeoally_nuern        @"Dangerous!!! Couldn't update the Keychain Item. result: %d"  //@"Dangerous!!! Couldn't update the Keychain Item. result: %d"
#define wwwww_tag_wwwww_largeory_ourie        @"Couldn't add the Keychain Item."  //@"Couldn't add the Keychain Item."
#define wwwww_tag_wwwww_behindproof_taskee        @"Adding the Keychain Item. result: %d"  //@"Adding the Keychain Item. result: %d"
#define wwwww_tag_wwwww_pylent_mandeous        @"Dangerous!!! Couldn't add the Keychain Item. result: %d"  //@"Dangerous!!! Couldn't add the Keychain Item. result: %d"
#define wwwww_tag_wwwww_com_dy_bundleSeedID        @"com.dy.bundleSeedID"  //@"com.dy.bundleSeedID"
#define wwwww_tag_wwwww_thousandism_redair        @"%@.com.dyKeyChainGroup"  //@"%@.com.dyKeyChainGroup"
#define wwwww_tag_wwwww_voracwise_sureward        @"%@.%@"  //@"%@.%@"
#define wwwww_tag_wwwww_squamcivilness_amph        @";/?:@&=$+{}<>,"  //@";/?:@&=$+{}<>,"
#define wwwww_tag_wwwww_text_plain        @"text/plain"  //@"text/plain"
#define wwwww_tag_wwwww_text_html        @"text/html"  //@"text/html"
#define wwwww_tag_wwwww_application_json        @"application/json"  //@"application/json"
#define wwwww_tag_wwwww_text_json        @"text/json"  //@"text/json"
#define wwwww_tag_wwwww_text_javascript        @"text/javascript"  //@"text/javascript"
#define wwwww_tag_wwwww_startfy_seget        @"MW_SDK get: path = %@,requsetHeader = %@,data = %@"  //@"MW_SDK get: path = %@,requsetHeader = %@,data = %@"
#define wwwww_tag_wwwww_Content_Type        @"Content-Type"  //@"Content-Type"
#define wwwww_tag_wwwww_charset        @"charset"  //@"charset"
#define wwwww_tag_wwwww_image_jpeg        @"image/jpeg"  //@"image/jpeg"
#define wwwww_tag_wwwww_pleious_sinistrbrotherally        @"Error: %@"  //@"Error: %@"
#define wwwww_tag_wwwww_fusarian_answership        @"accessToken=%@,userID=%@,displayName=%@"  //@"accessToken=%@,userID=%@,displayName=%@"
#define wwwww_tag_wwwww_sportsome_pilfaction        @"確   認"  //@"確   認"
#define wwwww_tag_wwwww_SDKBaseView_touchesBegan        @"SDKBaseView touchesBegan"  //@"SDKBaseView touchesBegan"
#define wwwww_tag_wwwww_initWithFrame        @"initWithFrame"  //@"initWithFrame"
#define wwwww_tag_wwwww_initWithCoder        @"initWithCoder"  //@"initWithCoder"
#define wwwww_tag_wwwww_init        @"init"  //@"init"
#define wwwww_tag_wwwww_raiseie_communityal        @"页面开始加载webView didStartProvisionalNavigation"  //@"页面开始加载webView didStartProvisionalNavigation"
#define wwwww_tag_wwwww_webView_didFailNavigation_withError        @"webView didFailNavigation withError"  //@"webView didFailNavigation withError"
#define wwwww_tag_wwwww_webView_decidePolicyForNavigationAction_decisionHandler        @"webView decidePolicyForNavigationAction decisionHandler"  //@"webView decidePolicyForNavigationAction decisionHandler"
#define wwwww_tag_wwwww_emea_taining        @"服务器重定向 didReceiveServerRedirectForProvisionalNavigation"  //@"服务器重定向 didReceiveServerRedirectForProvisionalNavigation"
#define wwwww_tag_wwwww_close        @"close"  //@"close"
#define wwwww_tag_wwwww_MWWebView_releaseAll        @"MWWebView releaseAll"  //@"MWWebView releaseAll"
#define wwwww_tag_wwwww_MWWebView_dealloc        @"MWWebView dealloc"  //@"MWWebView dealloc"
#define wwwww_tag_wwwww_sdk_social_banner_url        @"sdk_social_banner_url"  //@"sdk_social_banner_url"
#define wwwww_tag_wwwww_dichfollow_cultureorium        @"showSocialView url=%@"  //@"showSocialView url=%@"
#define wwwww_tag_wwwww_showSocialView_url_is_empty        @"showSocialView url is empty"  //@"showSocialView url is empty"
#define wwwww_tag_wwwww_BasePopupView_touchesBegan        @"BasePopupView touchesBegan"  //@"BasePopupView touchesBegan"
#define wwwww_tag_wwwww__CC_E2E2E2        @"#E2E2E2"  //@"#E2E2E2"
#define wwwww_tag_wwwww_officeraneity_accountern        @"%@image/sdk/%@/rebate_%@.png?t=%@"  //@"%@image/sdk/%@/rebate_%@.png?t=%@"
#define wwwww_tag_wwwww_ios        @"ios"  //@"ios"
#define wwwww_tag_wwwww_kin_telaceous        @"mUrlString = %@"  //@"mUrlString = %@"
#define wwwww_tag_wwwww_chantmemberly_ambiate        @"sender.tag=%d"  //@"sender.tag=%d"
#define wwwww_tag_wwwww_TAG_PAY_CHANNEL_OTHER        @"TAG_PAY_CHANNEL_OTHER"  //@"TAG_PAY_CHANNEL_OTHER"
#define wwwww_tag_wwwww_TAG_PAY_CHANNEL_APPLE        @"TAG_PAY_CHANNEL_APPLE"  //@"TAG_PAY_CHANNEL_APPLE"
#define wwwww_tag_wwwww_TAG_CLOSE        @"TAG_CLOSE"  //@"TAG_CLOSE"
#define wwwww_tag_wwwww_backUIView_gesture        @"backUIView gesture"  //@"backUIView gesture"
#define wwwww_tag_wwwww_genesory_clinist        @"請輸入6-20字元"  //@"請輸入6-20字元"
#define wwwww_tag_wwwww_fluxization_imagelet        @"textChanged=>%@"  //@"textChanged=>%@"
#define wwwww_tag_wwwww_Sign_in_with_Facebook        @"Sign in with Facebook"  //@"Sign in with Facebook"
#define wwwww_tag_wwwww_Sign_in_with_Apple        @"Sign in with Apple"  //@"Sign in with Apple"
#define wwwww_tag_wwwww_managerster_ratherage        @"MyTextFiled textChanged=>%@"  //@"MyTextFiled textChanged=>%@"
#define wwwww_tag_wwwww_AccountListViewCellID        @"AccountListViewCellID"  //@"AccountListViewCellID"
#define wwwww_tag_wwwww_milit_individual        @"didSelectRowAtIndexPath %ld"  //@"didSelectRowAtIndexPath %ld"
#define wwwww_tag_wwwww_request_code        @"request_code"  //@"request_code"
#define wwwww_tag_wwwww_2001        @"2001"  //@"2001"
#define wwwww_tag_wwwww_sarcage_stigmat        @"notice Url=%@"  //@"notice Url=%@"
#define wwwww_tag_wwwww_respondfaction_offeracy        @"%@(%@)"  //@"%@(%@)"
#define wwwww_tag_wwwww_movieaster_mulctious        @"termsUrl=%@"  //@"termsUrl=%@"
#define wwwww_tag_wwwww_curseer_sternitude        @"sdk/config/areaCode/areaInfo.json?t=%@"  //@"sdk/config/areaCode/areaInfo.json?t=%@"
#define wwwww_tag_wwwww_vivness_botanlegalance        @"sdk areaCode info:%@"  //@"sdk areaCode info:%@"
#define wwwww_tag_wwwww_environmentalatory_alteratfication        @"sdk/config/%@/v1/version.json?t=%@"  //@"sdk/config/%@/v1/version.json?t=%@"
#define wwwww_tag_wwwww_boardress_stationally        @"sdk config:%@"  //@"sdk config:%@"
#define wwwww_tag_wwwww_standmost_palplaytion        @"reportSdkEvent start EventName:%@"  //@"reportSdkEvent start EventName:%@"
#define wwwww_tag_wwwww_sdk_event_log        @"sdk/event/log"  //@"sdk/event/log"
#define wwwww_tag_wwwww_presidentacy_clausaneity        @"reportSdkEvent finish success EventName:%@"  //@"reportSdkEvent finish success EventName:%@"
#define wwwww_tag_wwwww_condiweightenne_director        @"reportSdkEvent finish error EventName:%@, errorMsg:%@"  //@"reportSdkEvent finish error EventName:%@, errorMsg:%@"
#define wwwww_tag_wwwww_languageize_attackitive        @"%@%@=%@&"  //@"%@%@=%@&"
#define wwwww_tag_wwwww_sdk_api_market_switch        @"sdk/api/market/switch"  //@"sdk/api/market/switch"
#define wwwww_tag_wwwww_phorcontainuous_glabrety        @"post: path = %@,requsetHeader = %@,data = %@"  //@"post: path = %@,requsetHeader = %@,data = %@"
#define wwwww_tag_wwwww_availableary_insteadism        @"sdk/config/%@/v1/market.json?t=%@"  //@"sdk/config/%@/v1/market.json?t=%@"
#define wwwww_tag_wwwww_sdk_api_market_articles        @"sdk/api/market/articles"  //@"sdk/api/market/articles"
#define wwwww_tag_wwwww_seato_especiallyise        @"market/articles:%@"  //@"market/articles:%@"
#define wwwww_tag_wwwww_uloproof_heartess        @"%@aKey=1"  //@"%@aKey=1"
#define wwwww_tag_wwwww_daughterless_pitair        @"%@&%@"  //@"%@&%@"
#define wwwww_tag_wwwww_finditious_threatence        @"%@?%@"  //@"%@?%@"
#define wwwww_tag_wwwww_X_User_AppId        @"X-User-AppId"  //@"X-User-AppId"
#define wwwww_tag_wwwww_X_User_Platform        @"X-User-Platform"  //@"X-User-Platform"
#define wwwww_tag_wwwww_donible_vorac        @"%@|%@|%@"  //@"%@|%@|%@"
#define wwwww_tag_wwwww_X_User_Device        @"X-User-Device"  //@"X-User-Device"
#define wwwww_tag_wwwww_X_App_Version        @"X-App-Version"  //@"X-App-Version"
#define wwwww_tag_wwwww_almot_locoture        @"get: path = %@,requsetHeader = %@, params = %@, data = %@"  //@"get: path = %@,requsetHeader = %@, params = %@, data = %@"
#define wwwww_tag_wwwww_exampleery_pubon        @"get: path = %@, error = %@"  //@"get: path = %@, error = %@"
#define wwwww_tag_wwwww_iratesque_ambi        @"post: path = %@,params = %@"  //@"post: path = %@,params = %@"
#define wwwww_tag_wwwww_findfy_brevability        @"post: path = %@, error = %@,requsetHeader = %@"  //@"post: path = %@, error = %@,requsetHeader = %@"
#define wwwww_tag_wwwww_ballistic_of        @"file upload: path = %@, error = %@"  //@"file upload: path = %@, error = %@"
#define wwwww_tag_wwwww_AccountModel_init        @"AccountModel init"  //@"AccountModel init"
#define wwwww_tag_wwwww_AccountModel_encodeWithCoder        @"AccountModel encodeWithCoder"  //@"AccountModel encodeWithCoder"
#define wwwww_tag_wwwww_AccountModel_initWithCoder        @"AccountModel initWithCoder"  //@"AccountModel initWithCoder"
#define wwwww_tag_wwwww_Helvetica_Bold        @"Helvetica-Bold"  //@"Helvetica-Bold"
#define wwwww_tag_wwwww_altity_fistulent        @"var meta = document.createElement('meta'); meta.setAttribute('name', 'viewport'); meta.setAttribute('content', 'width=device-width'); document.getElementsByTagName('head')[0].appendChild(meta);"  //@"var meta = document.createElement('meta'); meta.setAttribute('name', 'viewport'); meta.setAttribute('content', 'width=device-width'); document.getElementsByTagName('head')[0].appendChild(meta);"
#define wwwww_tag_wwwww_oality_muchet        @"^.+@\\w+\\..+$"  //@"^.+@\\w+\\..+$"
#define wwwww_tag_wwwww_laterer_path        @"[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}"  //@"[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}"
#define wwwww_tag_wwwww_sit_minditor        @"sdk_event_%@"  //@"sdk_event_%@"
#define wwwww_tag_wwwww_sdk_is14age        @"sdk_is14age"  //@"sdk_is14age"
#define wwwww_tag_wwwww_api_user_visitorLogin        @"api/user/visitorLogin"  //@"api/user/visitorLogin"
#define wwwww_tag_wwwww_api_user_thirdPartyLogin        @"api/user/thirdPartyLogin"  //@"api/user/thirdPartyLogin"
#define wwwww_tag_wwwww_api_user_register        @"api/user/register"  //@"api/user/register"
#define wwwww_tag_wwwww_api_user_login        @"api/user/login"  //@"api/user/login"
#define wwwww_tag_wwwww_api_pwd_forgotPassword        @"api/pwd/forgotPassword"  //@"api/pwd/forgotPassword"
#define wwwww_tag_wwwww_api_vcode_sendEmailVcode        @"api/vcode/sendEmailVcode"  //@"api/vcode/sendEmailVcode"
#define wwwww_tag_wwwww_api_pwd_changePassword        @"api/pwd/changePassword"  //@"api/pwd/changePassword"
#define wwwww_tag_wwwww_api_upgrade_bind        @"api/upgrade/bind"  //@"api/upgrade/bind"
#define wwwww_tag_wwwww_api_cancel_account        @"api/cancel/account"  //@"api/cancel/account"
#define wwwww_tag_wwwww_api_order_create        @"api/order/create"  //@"api/order/create"
#define wwwww_tag_wwwww_api_apple_payment        @"api/apple/payment"  //@"api/apple/payment"
#define wwwww_tag_wwwww_api_payment_channel        @"api/payment/channel"  //@"api/payment/channel"
#define wwwww_tag_wwwww_api_vcode_sendMobileVcode        @"api/vcode/sendMobileVcode"  //@"api/vcode/sendMobileVcode"
#define wwwww_tag_wwwww_api_mobile_bind        @"api/mobile/bind"  //@"api/mobile/bind"
#define wwwww_tag_wwwww_v_vn        @"v_vn"  //@"v_vn"
#define wwwww_tag_wwwww_pathyety_multamethoddom        @"authorization.credential：%@"  //@"authorization.credential：%@"
#define wwwww_tag_wwwww_necessary_altiory        @"mStr：%@"  //@"mStr：%@"
#define wwwww_tag_wwwww_ok_rotrateproof        @"错误信息：%@"  //@"错误信息：%@"
#define wwwww_tag_wwwww_highability_hirsutard        @"controller requests：%@"  //@"controller requests：%@"
#define wwwww_tag_wwwww_violenceative_pointsome        @"调用展示window方法：%s"  //@"调用展示window方法：%s"
#define wwwww_tag_wwwww_sdk_naver_consumer_key        @"sdk_naver_consumer_key"  //@"sdk_naver_consumer_key"
#define wwwww_tag_wwwww_sdk_naver_consumer_secret        @"sdk_naver_consumer_secret"  //@"sdk_naver_consumer_secret"
#define wwwww_tag_wwwww_also_quass        @"SCREEN_WIDTH:%f,SCREEN_HEIGHT:%f"  //@"SCREEN_WIDTH:%f,SCREEN_HEIGHT:%f"
#define wwwww_tag_wwwww_releaseReader        @"releaseReader"  //@"releaseReader"
#define wwwww_tag_wwwww_reader_init        @"reader init"  //@"reader init"
#define wwwww_tag_wwwww_areaInfo        @"areaInfo"  //@"areaInfo"
#define wwwww_tag_wwwww_irative_argentfaction        @"======================readMainBundleCoreConfInfo start ================="  //@"======================readMainBundleCoreConfInfo start ================="
#define wwwww_tag_wwwww_KEY        @"KEY"  //@"KEY"
#define wwwww_tag_wwwww_ovile_punsive        @"decryptContent eKey=%@,eIV=%@"  //@"decryptContent eKey=%@,eIV=%@"
#define wwwww_tag_wwwww_zh_Hant        @"zh-Hant"  //@"zh-Hant"
#define wwwww_tag_wwwww_zh_Hans        @"zh-Hans"  //@"zh-Hans"
#define wwwww_tag_wwwww_analysisenne_prolesar        @"languageStr=%@,md5EncryptFileName=%@,encryptStr=%@"  //@"languageStr=%@,md5EncryptFileName=%@,encryptStr=%@"
#define wwwww_tag_wwwww_deictsex_far        @"file not find : %@.json"  //@"file not find : %@.json"
#define wwwww_tag_wwwww_phobet_calletic        @"configInfoName=%@,md5EncryptFileName=%@,encryptStr=%@"  //@"configInfoName=%@,md5EncryptFileName=%@,encryptStr=%@"
#define wwwww_tag_wwwww_pantetic_pathoably        @"language = %@ not exist"  //@"language = %@ not exist"
#define wwwww_tag_wwwww_plodon_septi        @"set language str = %@"  //@"set language str = %@"
#define wwwww_tag_wwwww_claudad_laceracy        @"md5EncryptFileName=%@"  //@"md5EncryptFileName=%@"
#define wwwww_tag_wwwww_cordavailableacle_sequty        @"textEncrypContent =%@,textContent=%@"  //@"textEncrypContent =%@,textContent=%@"
#define wwwww_tag_wwwww_Localizable        @"Localizable"  //@"Localizable"
#define wwwww_tag_wwwww_gameCode        @"gameCode"  //@"gameCode"
#define wwwww_tag_wwwww_appKey        @"appKey"  //@"appKey"
#define wwwww_tag_wwwww_gameLanguage        @"gameLanguage"  //@"gameLanguage"
#define wwwww_tag_wwwww_zh_TW        @"zh_TW"  //@"zh_TW"
#define wwwww_tag_wwwww_zh_CN        @"zh_CN"  //@"zh_CN"
#define wwwww_tag_wwwww_en_US        @"en_US"  //@"en_US"
#define wwwww_tag_wwwww_vi_VN        @"vi_VN"  //@"vi_VN"
#define wwwww_tag_wwwww_ko_KR        @"ko_KR"  //@"ko_KR"
#define wwwww_tag_wwwww_sdk_url_login        @"sdk_url_login"  //@"sdk_url_login"
#define wwwww_tag_wwwww_sdk_url_pay        @"sdk_url_pay"  //@"sdk_url_pay"
#define wwwww_tag_wwwww_sdk_url_cdn        @"sdk_url_cdn"  //@"sdk_url_cdn"
#define wwwww_tag_wwwww_sdk_url_log        @"sdk_url_log"  //@"sdk_url_log"
#define wwwww_tag_wwwww_sdk_url_plat        @"sdk_url_plat"  //@"sdk_url_plat"
#define wwwww_tag_wwwww_terms_service_url        @"terms_service_url"  //@"terms_service_url"
#define wwwww_tag_wwwww_af_dev_key        @"af_dev_key"  //@"af_dev_key"
#define wwwww_tag_wwwww_sdk_appId        @"sdk_appId"  //@"sdk_appId"
#define wwwww_tag_wwwww_sdk_ad_bug        @"sdk_ad_bug"  //@"sdk_ad_bug"
#define wwwww_tag_wwwww_sdk_v_version        @"sdk_v_version"  //@"sdk_v_version"
#define wwwww_tag_wwwww_sdk_more_language        @"sdk_more_language"  //@"sdk_more_language"
#define wwwww_tag_wwwww_sdk_language        @"sdk_language"  //@"sdk_language"
#define wwwww_tag_wwwww_sdk_res_bundle_name        @"sdk_res_bundle_name"  //@"sdk_res_bundle_name"
#define wwwww_tag_wwwww_Info        @"Info"  //@"Info"
#define wwwww_tag_wwwww_FacebookAppID        @"FacebookAppID"  //@"FacebookAppID"
#define wwwww_tag_wwwww_DYDY128KEY        @"DYDY128KEY"  //@"DYDY128KEY"
#define wwwww_tag_wwwww_DYDY128IV        @"DYDY128IV"  //@"DYDY128IV"
#define wwwww_tag_wwwww__addTransactionObserver        @"-addTransactionObserver"  //@"-addTransactionObserver"
#define wwwww_tag_wwwww_detailally_bitance        @"checkOrderStatus 检测客户端与服务器漏单情况处理"  //@"checkOrderStatus 检测客户端与服务器漏单情况处理"
#define wwwww_tag_wwwww_cauliator_whileenne        @"开始补发:transactionId=%@,orderId=%@"  //@"开始补发:transactionId=%@,orderId=%@"
#define wwwww_tag_wwwww_priviibility_ris        @"完成补发:transactionId=%@,orderId=%@"  //@"完成补发:transactionId=%@,orderId=%@"
#define wwwww_tag_wwwww_radfier_fringitude        @"补发错误:transactionId=%@,orderId=%@"  //@"补发错误:transactionId=%@,orderId=%@"
#define wwwww_tag_wwwww_vet_individualery        @"Array of unfinished SKPaymentTransactions:%d"  //@"Array of unfinished SKPaymentTransactions:%d"
#define wwwww_tag_wwwww_error_cpOrderId_productId_empty        @"error:cpOrderId/productId empty"  //@"error:cpOrderId/productId empty"
#define wwwww_tag_wwwww_error_orderId_productId_empty        @"error:orderId/productId empty"  //@"error:orderId/productId empty"
#define wwwww_tag_wwwww_offertion_brachyible        @"-SKPaymentQueue canMakePayments]"  //@"-SKPaymentQueue canMakePayments]"
#define wwwww_tag_wwwww_In_app_purchases_are_not_supported        @"In-app purchases are not supported"  //@"In-app purchases are not supported"
#define wwwww_tag_wwwww__SKProductsRequest_start        @"-SKProductsRequest start"  //@"-SKProductsRequest start"
#define wwwww_tag_wwwww_solization_stataneous        @"发起付款-addPayment"  //@"发起付款-addPayment"
#define wwwww_tag_wwwww_bromine_gentet        @"Unable to fetch product, please try again"  //@"Unable to fetch product, please try again"
#define wwwww_tag_wwwww_create_cune        @"产品付费数量:%ld"  //@"产品付费数量:%ld"
#define wwwww_tag_wwwww_pulverless_scindot        @"------------------错误didFailWithError-----------------:%@"  //@"------------------错误didFailWithError-----------------:%@"
#define wwwww_tag_wwwww_Failed_to_get_product_information_from_Apple        @"Failed to get product information from Apple"  //@"Failed to get product information from Apple"
#define wwwww_tag_wwwww_pastate_emewise        @"------------反馈信息结束requestDidFinish-----------------%@"  //@"------------反馈信息结束requestDidFinish-----------------%@"
#define wwwww_tag_wwwww_modelibility_husbandature        @"购买成功 SKPaymentTransactionStatePurchased"  //@"购买成功 SKPaymentTransactionStatePurchased"
#define wwwww_tag_wwwww_velleade_deltlet        @"商品添加进列表 SKPaymentTransactionStatePurchasing"  //@"商品添加进列表 SKPaymentTransactionStatePurchasing"
#define wwwww_tag_wwwww_flucenter_bewithoutarian        @"交易失败:%@"  //@"交易失败:%@"
#define wwwww_tag_wwwww_SKPaymentTransactionStateDeferred        @"SKPaymentTransactionStateDeferred"  //@"SKPaymentTransactionStateDeferred"
#define wwwww_tag_wwwww_transactionId_is_empty        @"transactionId is empty"  //@"transactionId is empty"
#define wwwww_tag_wwwww_0000        @"0000"  //@"0000"
#define wwwww_tag_wwwww_bankivity_not        @"transactionId=%@本地记录存在,记录的orderId=%@"  //@"transactionId=%@本地记录存在,记录的orderId=%@"
#define wwwww_tag_wwwww_1000        @"1000"  //@"1000"
#define wwwww_tag_wwwww_1001        @"1001"  //@"1001"
#define wwwww_tag_wwwww_currentOrderId        @"currentOrderId"  //@"currentOrderId"
#define wwwww_tag_wwwww_transferOrderId        @"transferOrderId"  //@"transferOrderId"
#define wwwww_tag_wwwww_isOnPaying        @"isOnPaying"  //@"isOnPaying"
#define wwwww_tag_wwwww_payEnv        @"payEnv"  //@"payEnv"
#define wwwww_tag_wwwww_finishPayWithStatus_success        @"finishPayWithStatus success"  //@"finishPayWithStatus success"
#define wwwww_tag_wwwww_finishPayWithStatus_fail        @"finishPayWithStatus fail"  //@"finishPayWithStatus fail"
#define wwwww_tag_wwwww_kSaveReceiptData_MW        @"kSaveReceiptData_MW"  //@"kSaveReceiptData_MW"
#define wwwww_tag_wwwww_kSaveReceiptData_receiptData        @"kSaveReceiptData_receiptData"  //@"kSaveReceiptData_receiptData"
#define wwwww_tag_wwwww_kSaveReceiptData_orderId        @"kSaveReceiptData_orderId"  //@"kSaveReceiptData_orderId"
#define wwwww_tag_wwwww_kSaveReceiptData_transactionId        @"kSaveReceiptData_transactionId"  //@"kSaveReceiptData_transactionId"
#define wwwww_tag_wwwww_kSaveReceiptData_time        @"kSaveReceiptData_time"  //@"kSaveReceiptData_time"
#define wwwww_tag_wwwww__CC_02F0FE        @"#02F0FE"  //@"#02F0FE"
#define wwwww_tag_wwwww__CC_4FACFE        @"#4FACFE"  //@"#4FACFE"
#define wwwww_tag_wwwww__CC_00F2FE        @"#00F2FE"  //@"#00F2FE"
#define wwwww_tag_wwwww__CC_B1B1B1        @"#B1B1B1"  //@"#B1B1B1"

#endif /* Headers_h */
