#ifndef codeObfuscation_h
#define codeObfuscation_h

#ifdef SDK_CODE_OBFUSCATION  //是否开启方法混淆

#define accountRegister    podetteDiplfy
#define addAccountListTableView    quiteAmongular
#define addAccountListView    contraXiphture
#define addBindAccountView    scabiooonPluhood
#define addCellView    cipitieLacerish
#define addChangePasswordView    centralOpi
#define addContentView    calosecurityenCreatety
#define addContentView_v2    hippoeasttySiderarium
#define addDeleteAccountConfireView    paraPyl
#define addDeleteAccountView    sayeurPulchr
#define addFindPasswordView    partsiveSteper
#define addHomeView    stigeeIntereston
#define addLoginWithRegView    andraireBathoose
#define addSelectBindTypeView    reporttySource
#define addSubSdkLoginView    crevavoidLinard
#define addTermsView    eitherficImpactible
#define addView    changeuleFrontetic
#define addWelcomeView    cyanesquePteroage
#define appendCommParamsDic    petaciousVehette
#define appendGameParamsDic    caedNullseatous
#define appleLoginAndThirdRequest    silviFelibility
#define appleViewTapped    saceraireCharge
#define autoLoginAppleAccountWithInformation    menienManot
#define backBtnView    employeeproofCopresque
#define backUIView    phylaxonSpecialence
#define beforeStartTimer    copresqueMentule
#define bindAccount    typicalLaughfier
#define bindAccountAndRequest    badetPrimoeverybodyit
#define bindAccountPhone    suinessOmniot
#define bundleSeedID    bisettePatientation
#define calculateSizeOfLabel    umbiliceerPessimfarant
#define cancelAutoSwitchAccount    gnarenneOperguyical
#define changPasswordSuccess    ceasionSeptuagenably
#define changePassword    laborthoughismMonthance
#define checkAgreeTerm    wholeVolvly
#define checkOrderStatus    scansoseRichair
#define checkParams    battbetterLiquid
#define checkValue    vasesqueGranern
#define clickItemBtn    archykinSebihappensive
#define colorWithHexString    cephaloaboutialOureous
#define copyConfigeFileToDocument    cordathoodGrameer
#define creatDelegateWithBack    endatorProximress
#define createOrderWithproductId    glacinothingacyWaitee
#define createSdkUrl    paedoPeculi
#define customUUID    soncyTorror
#define requestDeleteUserAccount    studentBeforeoon
#define deleteAccountAndRequest    quadragenThroughform
#define doAccountBindingWithUserName    degreeLamnlamelletic
#define doChangePasswordWithUserName    scindeverythingHydroment
#define doDeleteAccount    penneeLittleability
#define doFacebookBindingWithUserName    notlingConcernesque
#define doFacebookBindingwithUserID    wayialGreato
#define doForgotPasswordWithUserName    homefulOrbcultureule
#define doLoginWithAccount    benonearyTax
#define doLoginWithFacebook    gnarSculpt
#define doRegisterAccountWithUserName    scrupulformRestain
#define doTiming    actuallyialCusplie
#define eyeViewBtnAction    sceptsiveTreaton
#define facebookLogout    possibleiaSizesive
#define fbLoginAndThirdRequest    manthemorFoenlike
#define fetchAppleLoginInfo    seboateOpoidentifycy
#define fetchPhoneAreaInfo    septimingMajie
#define fileUploadWithFunctionPath    behindryBenefit
#define findPassword    lacerdefenseSite
#define finishCountTimer    pinnCentesimee
#define finishPayWithStatus    denfulTorration
#define finishTimer    beyondletHolothanfier
#define freeLoginOrRegister    structureoryWithinivity
#define gama_AES128DecryptWithKey    orbticFilcost
#define gama_AES128EncryptWithKey    visousDeathit
#define gama_AES128Operation    capfoldFaceature
#define gama_boundsForOrientation    largeControlable
#define gama_currentBounds    crurFraternoon
#define gama_hiddenPlatform    dexterSciglassry
#define gama_imageNamed    licteryPhalarwideward
#define gama_mainScreenBounds    homitorLanguile
#define gama_screenScale    friendierMaintainitious
#define getAccountModels    speciorWantaster
#define getAfDevKey    formfyQuatien
#define getAppId    decisioneurAgent
#define getAppkey    cerebristCatenitious
#define getAreaInfoWithSuccessBlock    ledendLystness
#define getBoolForKey_WLFuncTag    amicionFerrose
//#define getBuffer    amattyTaxsure
#define getBundleIdentifier    societySeptiform
#define getBundleName    campaignanceStoryard
#define getBundleShortVersionString    colegalenMandsive
#define getBundleVersion    tetanpulleurJocmeaneity
#define getCdnUrl    pantlessReduce
#define getCfUUID    agrfySeaor
#define getClientID    chairallyStreptia
#define getCurrentScreenFrame    mrfierOccuresque
#define getCurrentViewController    monoernSouthernition
#define getCurrentWindow    prendapproachAnnivity
#define getCustomCfUUID    herbatureFungaccountive
#define getDecryptDataFromData    predMouthty
#define getDecryptStringFromString_WLFuncTag    causThoughtous
#define getDeviceType    phasadeRoadivity
#define getDeviceVersion    practiceishNephr
#define getEncodeDataFromString    arborSerrstationar
#define getEncodeStringFromData    feelmostSitely
#define getEncryptDataFromData    emetelStearate
#define getEncryptStringFromString    narticGam
#define getFacebookAppId    fratrVelleality
#define getFontSize    itemallyIncrease
#define getGamaCfUUIDFromPublicKeychain    famityGalacthearile
#define getGamaUUID    thelDuring
#define getGameCode    salutsocialibleStillition
#define getGameLanguage    hyperetExtraess
#define getIPAddress    carniitorOfferform
#define getIdfa    apertshipMeterel
#define getLocalReceiptData    produceNihilsion
#define getLocalizedStringForKey_WLFuncTag    populativeEnjoy
#define getLoginUrl    leadeticArborinstitution
#define getMD5StrFromString    credareaoseDegreeious
#define getMacaddress    areaairRemove
#define getPayUrl    enjoyressTextory
#define getPhoneAreaCode    ornTranacity
#define getPhoneNumber    myselfuleCosmlike
#define getPreferredLanguage    tectdogialPossiblead
#define getProjectInfoPlist    televisionileVelleous
#define getRequestWithFunctionPath    phylactAlgia
#define postRequestWithFunctionPath    detailableAlter
#define getSdkBundleName_WLFuncTag    dactyliokindGelent
#define getSdkConfigWithSuccessBlock    claustroActivityward
#define getServerLanguage    templizeMustive
#define getServerLocaleStrWithGameLanguage    conallyFirmation
#define getShowBtnDatas    sputlingDecisionory
#define getStringForKey_WLFuncTag    arboriPinsive
#define getSystemVersion    stegsureSexagesimfier
#define getTermsServiceUrl    mentarianScrupesque
#define getTimeDate    fancSpondylexistast
#define getTimeStamp    violenceVicety
#define getTodayInfo    cinerariumEveryal
#define getUserInfo    dipsohoodMajorityar
#define getViewHeight    expectotParian
#define getViewWidth    carcerAurietic
#define goBackBtn    sciFieldose
#define goGame    votsafesomeSegless
#define goPageView    songmostGetwise
#define googleLoginAndThirdRequest    neineClyscampaignical
#define guestLoginAndThirdRequest    successalityCitizenive
#define handleAuthrization    fringiseOntoorium
#define handleLoginOrRegSuccess    dreamfyLessast
#define handleSignInWithAppleStateChanged    keepkinFundion
#define isAdDebug    plesiPaternify
#define isAgreenProvision    plusAlways
#define isContainString    ordericeImpacttic
#define isFacebookLogined    carcereousManageior
#define isIPhoneXSeries    semaoThinkative
#define isMoreLanguage    hereYeahatory
#define isNotEmpty    teronGenaron
#define isRequestSuccess    futilcontrolRuriular
#define isVersion2    statementcyDictatic
#define itemBtnAction    selleerMounter
#define landspaceView    partshipRobor
#define lineLoginAndThirdRequest    gramoGreat
#define localx    siliatureMovementacle
#define logEventPurchaseValues    uliginespeciallyanFutureior
#define logEventWithEventName    sulcCratior
#define logWithEventName    dictitiousCaptward
#define loginDecryptFromString    gamekinRaucdesignical
#define loginEncryptFromString    triborFalclevelesque
#define loginSuccess    kinessureReflect
#define loginWithClientID    exactlyativeForeignling
#define loginWithPerssion    issuearyInosity
#define loginWithPesentingViewController    rapaciularPoor
#define makeAccountFiledViewStatus    cantWhateverosity
#define makeAppleCallbackSuccessBlock    tetrenceGuyier
#define makeTabStatus    standardositySpician
#define numberTimesAtString    vicesimionMnes
#define openProvision    hypaneityStatementia
#define phoneFireTimer    herbPartenne
#define pushAreaTable    cauliTeloorium
#define readCoreConfInfo    historyativePall
#define readMainBundleCoreConfInfo_WLFuncTag    tinacigenerationablyPleward
#define rectFromWinSize_Landscape    nulliveAtade
#define rectFromWinSize_Portrait    pepswiseGust
#define registNotification    prolesanceRecentatic
#define registerViewBtnAction    raphismCoursetion
#define reloadCoreConf    epistemshipTeretacious
#define removeAccountByLoginType    liberFallfold
#define removeAccountByUserId    sulcationTranhit
#define removeAllUncompleteTransactionsBeforeNewPurchase    geosionCosmture
#define removeLocReceiptDataByTranId    valativePhrenform
#define requestAccountLogin    closeousVerimagazineably
#define requestMobileVfCode    rubrballtyNugaary
#define requestVfCodeByEmail    unisiveCerebroeur
#define res_imageNamed    formOctlet
#define resetKeychainItem    easyarContratic
#define resetVfCodeBtnStatue    currVagaeer
#define resetupAreaCodesAndActionSheetWith    aboutivityRhyncher
#define saveAccountModel    owneryOntoably
#define saveAccountModels    becauseeousMunooftenfier
#define saveAgreenProvisionState    mesofierAccount
#define saveAppleLastLoginSuccessWithInformation    tortuageSeatery
#define saveCfUUID    gardenPrincardain
#define saveLoginType    testieLeproaneous
#define savePhoneAreaInfo    especiallyiaMoveory
#define saveReceiptData    yeterFet
#define saveUserInfo    emetiuousHypty
#define sdkLoginWithHandlerForInner_WLFuncTag    agencyityRisk
#define sdk_application    nectistRadic
#define sdk_applicationDidBecomeActive    anthropoicPlethadministration
#define sdk_applicationDidEnterBackground    ducacleSagittboardess
#define sdk_applicationWillEnterForeground    addorFilmia
#define sdk_applicationWillTerminate    equiservicewiseLetfy
#define secItemFormatToDictionary    goodOdonie
#define selfLoginAndRequest    susionTernress
#define setGameLanguage    fluarLayics
#define setNeedUpdate    rotsuccessfulageEndization
#define setPwdFiledView    unguialitySendit
#define setViewStatue    laudardBoytion
//#define shouldAutorotate    superpositionarianCondine
#define showActionSheetWithTitle    fendSpecsive
#define showAlertTips    concernacityCellacle
#define showAlertViewWithTitle    audacLearn
#define showAlertWithMessage    verificPlinthior
#define showAreaCodesActionSheetFromView    layibilityMoveature
#define showIpadActionSheet    lefterSedecitious
#define showLoadingAtView    nectspecialosityOmasdeepship
#define showLoginPageOrAutoLogin    amorileHemosity
#define showSelectedAreaCodeValue    tinctaticAstro
#define startCountTimer    aroundidWindally
#define startLoginWithCallBack    typoonPlexform
//#define startMonitoring    solvableTreatistic
#define startPayWithProductId    proletinstitutionainCortit
#define stopLoadingAtView    treearyMovieize
#define stringToMd5    interprocessHairain
#define thirdLoginOrReg    materialEverybodylike
#define timing    ultramustuousStartier
#define titleFontWedthWithMaxStr    uniPantsive
#define toastMsg    playerisePneuize
#define urlEcodingFromString    hemiAlglateraneity
#define urlEncodeString    auctCommercialosity
#define validEmail    sexagensexualfactionStock
#define validPhone    visFring
#define validPwd    mostPredrepublicanacy
#define validUserName    majoriseSalutopportunity
#define paymentWithTransactionId    sesquipositiveOlitive

#define getSdkEncryptKey_WLFuncTag sxxesqandPlayOli
#define WithKey_WLFuncTag  aaaKeyHelp
#define iv_WLFuncTag  mmxIvValue

#define getSdkConfigInfoName_WLFuncTag  getJJSCinfugName
#define getMySdkBundle_WLFuncTag getMyMDSSdkBundle
#define getSdkBundleFilePath_WLFuncTag  getSdkKAFHEUFBundleFilePath
#define ofType_WLFuncTag fieladofType
#define setBundleInfo_WLFuncTag   setJppdBundleaaeInfo
#define getEncryptFileAndEncryptContentWithBundle_WLFuncTag   getEncryptFileAndEncryptContentWithBundle
#define  name_WLFuncTag amdakFileName
#define logSdkResConfig_WLFuncTag     logSdkResConfig
#define getSdkBaseEncryptKey_WLFuncTag    getSdkBaseEncryptKey
#define decryptAllStringContent_WLFuncTag   decryptAllStringContent_WLFuncTag
#else

#endif

#endif  /* codeObfuscation_h */
