#ifndef codeObfuscation_h
#define codeObfuscation_h

#ifdef SDK_CODE_OBFUSCATION  //是否开启方法混淆
#define accountRegister   sufUberunitie
#define addAccountListTableView   withoutatoryFlectan
#define addAccountListView   yetotUrsfinditude
#define addBindAccountView   applyeousNau
#define addCellView   caulresponsibilityyWest
#define addChangePasswordView   fligEofication
#define addContentView   ephNicearium
#define addContentView_v2   lysernLearnaceous
#define addDeleteAccountConfireView   vicoveritudeCarefication
#define addDeleteAccountView   fasticePhotacious
#define addFindPasswordView   optoBuccseaably
#define addHomeView   buildinglyPerhapsling
#define addLoginWithRegView   meningPlayoon
#define addSelectBindTypeView   painHerster
#define addSubSdkLoginView   directorsionTherioably
#define addTermsView   decorriseCityry
#define addView   ludacitySolit
#define addWelcomeView   ocitionRegkindlike
#define appendCommParamsDic   probuleNasety
#define appendGameParamsDic   frigitudeSituationitive
#define appleLoginAndThirdRequest   cardEitherist
#define appleViewTapped   votespeciallyacityVertivity
#define autoLoginAppleAccountWithInformation   claudproduceadTropice
#define backBtnView   fugitasterAurless
#define backUIView   scensateLeuker
#define beforeStartTimer   cenGrowent
#define bindAccount   creasPreterize
#define bindAccountAndRequest   agefulNodious
#define bindAccountPhone   stenidTalkship
#define bundleSeedID   phalarsexualPantoier
#define calculateSizeOfLabel   feelingoNonagesimrange
#define cancelAutoSwitchAccount   enterarCusreality
#define changPasswordSuccess   augibilityBisward
#define changePassword   groundageDiscussatic
#define checkAgreeTerm   practiceshipGraphoesque
#define checkOrderStatus   amountorNegmost
#define checkParams   psychityOsair
#define checkValue   eastwardPraefoodice
#define clickItemBtn   algiaisticDecen
#define colorWithHexString   operarFinally
#define copyConfigeFileToDocument   kakorAlgenne
#define creatDelegateWithBack   poseousVorit
#define createOrderWithproductId   performAnyone
#define createSdkUrl   erriteGnarfier
#define customUUID   buildmostLotsion
#define requestDeleteUserAccount   acrLifeence
#define deleteAccountAndRequest   proliProduceent
#define doAccountBindingWithUserName   pravDogwise
#define doChangePasswordWithUserName   lightfierBecomeetic
#define doDeleteAccount   theiretteApert
#define doFacebookBindingWithUserName   scabimeasureCupitious
#define doFacebookBindingwithUserID   dexteracyPara
#define doForgotPasswordWithUserName   dieeWhileaneous
#define doLoginWithAccount   examplementSalvite
#define doLoginWithFacebook   dinneribleHerster
#define doRegisterAccountWithUserName   wantletHospitalably
#define doTiming   cerebroMeeteur
#define eyeViewBtnAction   dysdayfulAmphaneous
#define facebookLogout   weekitionLimacenne
#define fbLoginAndThirdRequest   closCost
#define fetchAppleLoginInfo   specificiousOssshoulderful
#define fetchPhoneAreaInfo   sculpCarpth
#define fileUploadWithFunctionPath   ofastLight
#define findPassword   lecitheticKlept
#define finishCountTimer   pendationHedoistic
#define finishPayWithStatus   stringatureScienceation
#define finishTimer   perhapseerPersonalfaction
#define freeLoginOrRegister   individuallikeTorristic
#define gama_AES128DecryptWithKey   nictsureLax
#define gama_AES128EncryptWithKey   furtateBager
#define gama_AES128Operation   rhombontoadeNegally
#define gama_boundsForOrientation   commonlikeThroughly
#define gama_currentBounds   storyeryOviacle
#define gama_hiddenPlatform   prehensadHeartel
#define gama_imageNamed   noxproofEtymible
#define gama_mainScreenBounds   countryivePlecitive
#define gama_screenScale   takeEither
#define gama_showPlatformToView   hereeousSatacle
#define getAccountModels   sinuaryPain
#define getAfDevKey   aboutibleHemification
#define getAppId   generalarMyselfitive
#define getAppkey   viiceEarlyable
#define getAreaInfoWithSuccessBlock   optoPropertyible
#define getBoolForKey   dinnerianBothitive
//#define getBuffer   fumuousBoload
#define getBundleIdentifier   miranDocureduceia
#define getBundleName   costBank
#define getBundleShortVersionString   somniHendecageeer
#define getBundleVersion   puniTers
#define getCdnUrl   cotylainDexterth
#define getCfUUID   motishFineular
#define getClientID   stringatureProduceent
#define getCurrentScreenFrame   facThenel
#define getCurrentViewController   cernitionTheseable
#define getCurrentWindow   fugalityProliess
#define getCustomCfUUID   plumSolit
#define getDecryptDataFromData   aerHousear
#define getDecryptStringFromString   morealitySuperise
#define getDeviceType   cipitalongibleContinueatory
#define getDeviceVersion   juxtaVidcontainling
#define getEncodeDataFromString   amouriceNoteitious
#define getEncodeStringFromData   timelyRhomb
#define getEncryptDataFromData   includingicalEducation
#define getEncryptStringFromString   candidatetureLaminoilfaction
#define getFacebookAppId   avoidTakeize
#define getFontSize   wonderFlammfication
#define getGamaCfUUIDFromPublicKeychain   wifeHeavyive
#define getGamaUUID   morningeerSorptise
#define getGameCode   onomaseasthoodPlagi
#define getGameLanguage   vomyourselfiseJudicfederalsure
#define getIPAddress   seniorsureStrigos
#define getIdfa   passerOleade
#define getLocalReceiptData   theroryMontfic
#define getLocalizedStringForKey   produceParticipantit
#define getLoginUrl   windotCalori
#define getMD5StrFromString   muneryDocible
#define getMacaddress   sorcieCineenne
#define getPayUrl   censcienceeeHoldery
#define getPhoneAreaCode   octogenRecordsion
#define getPhoneNumber   ecclesoforDis
#define getPreferredLanguage   takeSuddenlyster
#define getProjectInfoPlist   landletLike
#define getRequestWithFunctionPath   socitionDenlarge
#define postRequestWithFunctionPath     goodPostSion
#define getSdkBundleName   nonagesimrangeCortico
#define getSdkConfigWithSuccessBlock   seiicsIs
#define getServerLanguage   trabwhileeerLetenne
#define getServerLocaleStrWithGameLanguage   levelyCertain
#define getShowBtnDatas   fugarianNaissauthorfic
#define getStringForKey   bilsterPhiledefenseing
#define getSystemVersion   courmostUnguichair
#define getTermsServiceUrl   fricadCatenade
#define getTimeDate   serviceDealot
#define getTimeStamp   vigesimaticClystmajor
#define getTodayInfo   entericsPhanee
#define getUserInfo   electionardPrunid
#define getViewHeight   fluxKinetship
#define getViewWidth   tremuleNaissauthorfic
#define goBackBtn   genarMalleo
#define goGame   sacrooseQuiteial
#define goPageView   carniFicency
#define googleLoginAndThirdRequest   furtateThusality
#define guestLoginAndThirdRequest   phlegwardArctel
#define handleAuthrization   jutsureArchaify
#define handleLoginOrRegSuccess   bromoquicklyfoldToxreasonature
#define handleSignInWithAppleStateChanged   acusiveBibital
#define isAdDebug   folialVan
#define isAgreenProvision   niceariumRecently
#define isContainString   xanthagePhylacty
#define isFacebookLogined   rhombryDinnerian
#define isIPhoneXSeries   plutformBorance
#define isMoreLanguage   plectalityXiphbadar
#define isNotEmpty   tropsomePhantaneous
#define isRequestSuccess   missManagearium
#define isVersion2   parernCulinible
#define itemBtnAction   retauthorRich
#define landspaceView   tondyPalliics
#define lineLoginAndThirdRequest   armesqueAbout
#define localx   liqutruthiaTexly
#define logEventPurchaseValues   villalityMaintainad
#define logEventWithEventName   hirsutlossfierOpiine
#define logWithEventName   pangistTimacle
#define loginDecryptFromString   nothingHostian
#define loginEncryptFromString   severalistTrapez
#define loginSuccess   momentnessPeriodth
#define loginWithClientID   boranceUsing
#define loginWithPerssion   understandierAoon
#define loginWithPesentingViewController   forwardPubertette
#define makeAccountFiledViewStatus   acrosslikeExperitor
#define makeAppleCallbackSuccessBlock   plectalityAwayade
#define makeTabStatus   animalitiveSuperor
#define numberTimesAtString   barbCornthank
#define openProvision   tenachoodSmileaneous
#define phoneFireTimer   scabioifyEnterar
#define pushAreaTable   amatadeTenast
#define readCoreConfInfo   sacHerselffication
#define readMainBundleCoreConfInfo   flectticPolicain
#define rectFromWinSize_Landscape   seniorsureHyoaceous
#define rectFromWinSize_Portrait   amouriceControleous
#define registNotification   kleptCineenne
#define registerViewBtnAction   heatacyIdecustomer
#define reloadCoreConf   paucDis
#define removeAccountByLoginType   orexiabyingLigive
#define removeAccountByUserId   quinqueproofHabiltownon
#define removeAllUncompleteTransactionsBeforeNewPurchase   politicsFicency
#define removeLocReceiptDataByTranId   matterLikeuous
#define requestAccountLogin   dowTrigesimadministrationtic
#define requestMobileVfCode   pendationCenslike
#define requestVfCodeByEmail   authorsureFigaster
#define res_imageNamed   bilotheronNugaible
#define resetKeychainItem   issueScopesome
#define resetVfCodeBtnStatue   earlythSceneacle
#define resetupAreaCodesAndActionSheetWith   trabizePoliticsorium
#define saveAccountModel   phylcoachivityBooket
#define saveAccountModels   manyicalShoulderit
#define saveAgreenProvisionState   axiwhoseelTerrontoitor
#define saveAppleLastLoginSuccessWithInformation   palinanceAcance
#define saveCfUUID   canCephal
#define saveLoginType   rightVit
#define savePhoneAreaInfo   sisterenceTreeosity
#define saveReceiptData   uberunitieCauseety
#define saveUserInfo   sicceeCausemost
#define sdkLoginWithHandlerForInner   scendsomeMean
#define sdk_application   degreeerJuvenuous
#define sdk_applicationDidBecomeActive   genilyFulg
#define sdk_applicationDidEnterBackground   todayationCinehood
#define sdk_applicationWillEnterForeground   basiernMeretship
#define sdk_applicationWillTerminate   picturesureLedic
#define secItemFormatToDictionary   causemostAlreadyenne
#define selfLoginAndRequest   spufulAgr
#define setGameLanguage   treiskaidekdifficultularTrachyite
#define setNeedUpdate   recentlySalvar
#define setPwdFiledView   mitfierLubrictheorysive
#define setViewStatue   carpthGravier
#define shouldAutorotate   peacelessAllowety
#define showActionSheetWithTitle   manthpersonturePrettyation
#define showAlertTips   superencyItsance
#define showAlertViewWithTitle   entericsMammacity
#define showAlertWithMessage   uvairCaldion
#define showAreaCodesActionSheetFromView   holdTentile
#define showIpadActionSheet   omasthingSell
#define showLoadingAtView   relationshipAndity
#define showLoginPageOrAutoLogin   radioformFumuous
#define showSelectedAreaCodeValue   systemadeNespeechation
#define startCountTimer   tendicMrair
#define startLoginWithCallBack   kinyearfulAfterally
#define startMonitoring   plebatureRaceast
#define startPayWithProductId   templaboveessEnvironmentitude
#define stopLoadingAtView   gustBuccseaably
#define stringToMd5   saccibilityOdontize
#define thirdLoginOrReg   vagaquestionshipTreeosity
#define timing   opacyRhagbusinessitor
#define titleFontWedthWithMaxStr   miradTraical
#define toastMsg   itslikeSimilarior
#define urlEcodingFromString   amouriceRhag
#define urlEncodeString   sapiDis
#define validEmail   habiltownonCare
#define validPhone   felinstateaceousHugeent
#define validPwd   todayationBrachyial
#define validUserName   irascPylel
#define paymentWithTransactionId   irascJJSAPPylel

#else

#endif

#endif  /* codeObfuscation_h */
